import { createClient } from '@libsql/client';
import { randomUUID } from 'crypto';

const client = createClient({ url: 'file:local.db' });

const questions = [
  { channel: 'system-design', sub_channel: 'web-systems', difficulty: 'intermediate', question: 'Design a URL shortening service like bit.ly. What are the key components?', answer: 'Key components: API server, database (for URL mappings), cache (Redis), load balancer. Use base-62 encoding for short codes. Store: shortCode → originalURL. Consider scalability with read replicas and CDN.', explanation: 'URL shorteners need: unique key generation, fast redirect lookups, and analytics tracking. The bottleneck is read performance since redirects vastly outnumber writes.', tags: '["scalability","databases","caching"]' },
  { channel: 'system-design', sub_channel: 'distributed-systems', difficulty: 'advanced', question: 'How would you design a distributed cache system?', answer: 'Use consistent hashing for key distribution across nodes. Implement cache eviction policies (LRU, LFU). Handle cache invalidation, replication for fault tolerance, and partition tolerance.', explanation: 'Distributed caches must balance consistency, availability, and partition tolerance (CAP theorem). Consistent hashing minimizes cache misses when nodes are added/removed.', tags: '["caching","distributed","consistency"]' },
  { channel: 'system-design', sub_channel: 'real-time', difficulty: 'advanced', question: 'Design a real-time notification system for a social network.', answer: 'Use WebSockets or Server-Sent Events for real-time delivery. Message queue (Kafka/RabbitMQ) for decoupling. Push notifications via APNs/FCM for mobile. Store unread notifications in DB.', explanation: 'Real-time systems require persistent connections (WebSockets) and event-driven architectures. Decoupling producers from consumers with message queues enables horizontal scaling.', tags: '["websockets","notifications","messaging"]' },
  { channel: 'algorithms', sub_channel: 'graph-algorithms', difficulty: 'beginner', question: 'Explain the difference between BFS and DFS. When would you use each?', answer: 'BFS uses a queue, explores level by level - ideal for shortest path in unweighted graphs. DFS uses a stack (or recursion), explores depth first - ideal for cycle detection, topological sort, connected components.', explanation: 'BFS guarantees shortest path in unweighted graphs. DFS uses less memory for deep graphs. Both are O(V+E) for time and space complexity.', tags: '["graphs","traversal","BFS","DFS"]' },
  { channel: 'algorithms', sub_channel: 'dynamic-programming', difficulty: 'intermediate', question: 'What is dynamic programming? Give an example.', answer: 'DP solves problems by breaking them into overlapping subproblems, storing solutions to avoid recomputation. Example: Fibonacci - F(n) = F(n-1) + F(n-2). Memoization (top-down) or tabulation (bottom-up).', explanation: 'Two conditions needed for DP: optimal substructure (optimal solution contains optimal sub-solutions) and overlapping subproblems (same subproblems solved multiple times).', tags: '["DP","memoization","optimization"]' },
  { channel: 'algorithms', sub_channel: 'complexity', difficulty: 'beginner', question: 'Explain Big O notation. What is the time complexity of binary search?', answer: 'Big O describes worst-case time/space complexity as input grows. Binary search: O(log n) - divides search space in half each step. O(1) is constant, O(n) linear, O(n²) quadratic.', explanation: 'Binary search works on sorted arrays by comparing the target with the middle element and discarding half the remaining elements each iteration - hence O(log n).', tags: '["complexity","Big-O","binary-search"]' },
  { channel: 'frontend', sub_channel: 'react', difficulty: 'intermediate', question: 'What is the Virtual DOM in React and how does it improve performance?', answer: 'The Virtual DOM is a lightweight in-memory representation of the real DOM. React diffs the virtual DOM trees (reconciliation) to find minimal changes, then batches DOM updates.', explanation: 'Direct DOM manipulation is expensive. React batches updates using the virtual DOM diffing algorithm (Fiber in React 16+), minimizing reflows and repaints for better performance.', tags: '["react","virtual-dom","performance"]' },
  { channel: 'frontend', sub_channel: 'css', difficulty: 'beginner', question: 'Explain the CSS Box Model.', answer: 'The CSS Box Model consists of: content (actual content), padding (space inside border), border (surrounds padding), margin (space outside border). box-sizing: border-box makes width include padding+border.', explanation: 'Understanding the box model is crucial for precise layouts. By default (content-box), width/height only apply to content area. border-box is preferred in modern CSS for predictable sizing.', tags: '["css","layout","box-model"]' },
  { channel: 'frontend', sub_channel: 'react', difficulty: 'beginner', question: 'What are React Hooks? Name the most common ones.', answer: 'Hooks let functional components use state and lifecycle features. Common hooks: useState (local state), useEffect (side effects), useContext (context API), useRef (mutable refs), useMemo/useCallback (memoization).', explanation: 'Hooks were introduced in React 16.8 to replace class components. They follow two rules: only call at the top level, only call from React functions.', tags: '["react","hooks","state"]' },
  { channel: 'backend', sub_channel: 'api-design', difficulty: 'intermediate', question: 'What is the difference between REST and GraphQL?', answer: 'REST: multiple endpoints, fixed data structures, uses HTTP verbs. GraphQL: single endpoint, client specifies exact data needs, avoids over/under-fetching.', explanation: 'REST is simpler and more cacheable. GraphQL excels when clients need varying subsets of data. GraphQL reduces round-trips but adds complexity with schema definitions and resolvers.', tags: '["REST","GraphQL","API"]' },
  { channel: 'backend', sub_channel: 'databases', difficulty: 'intermediate', question: 'Explain database indexing. When should you use it?', answer: 'Indexes speed up data retrieval by creating sorted data structures (B-trees). Use for: columns in WHERE clauses, JOIN conditions, ORDER BY columns. Trade-off: faster reads, slower writes, more storage.', explanation: 'B-tree indexes provide O(log n) lookups. Covering indexes include all query columns, avoiding table lookups. Partial indexes on filtered subsets can be more efficient.', tags: '["database","indexing","performance"]' },
  { channel: 'devops', sub_channel: 'containers', difficulty: 'beginner', question: 'What is Docker and what problem does it solve?', answer: 'Docker is a containerization platform that packages apps with dependencies. Solves "works on my machine" problem by providing consistent environments. Containers are lightweight, portable, and isolated.', explanation: 'Containers share the host OS kernel but have isolated filesystems, processes, and networks. Unlike VMs, containers start in milliseconds and use far less resources.', tags: '["docker","containers","devops"]' },
  { channel: 'devops', sub_channel: 'ci-cd', difficulty: 'beginner', question: 'Explain CI/CD pipeline. What are the typical stages?', answer: 'CI/CD automates building, testing, and deploying code. Typical stages: Source → Build → Test → Deploy to staging → Integration tests → Deploy to production.', explanation: 'CI (Continuous Integration) automatically merges and tests code changes. CD (Continuous Delivery/Deployment) automates release to staging or production. This reduces manual errors and deployment frequency.', tags: '["CI/CD","automation","deployment"]' },
  { channel: 'data-structures', sub_channel: 'hash-tables', difficulty: 'intermediate', question: 'What is a hash table and how does collision resolution work?', answer: 'Hash table maps keys to values using a hash function. Collision resolution: chaining (linked list at each bucket) or open addressing (linear probing, quadratic probing, double hashing). Average O(1) for insert/search/delete.', explanation: 'A good hash function distributes keys uniformly. Load factor (n/m where n=elements, m=buckets) determines performance. Rehashing occurs when load factor exceeds a threshold (typically 0.75).', tags: '["hash-table","collision","data-structures"]' },
  { channel: 'data-structures', sub_channel: 'linear', difficulty: 'beginner', question: 'Explain the difference between a stack and a queue.', answer: 'Stack: LIFO (Last In First Out) - push/pop from same end. Use cases: function calls, undo operations, DFS. Queue: FIFO (First In First Out) - enqueue at back, dequeue from front. Use cases: BFS, scheduling, messaging.', explanation: 'Both are abstract data types. Stacks can be implemented with arrays or linked lists. Queues often use circular arrays for efficiency or linked lists to avoid overflow.', tags: '["stack","queue","data-structures"]' },
  { channel: 'kubernetes', sub_channel: 'core-concepts', difficulty: 'beginner', question: 'What is Kubernetes and what problems does it solve?', answer: 'Kubernetes is a container orchestration platform that automates deployment, scaling, and management of containerized apps. Solves: service discovery, load balancing, storage orchestration, automated rollouts/rollbacks, self-healing.', explanation: 'Kubernetes abstracts the underlying infrastructure, letting you declare desired state. The control plane continuously reconciles actual state with desired state through controllers.', tags: '["kubernetes","orchestration","containers"]' },
  { channel: 'aws', sub_channel: 'compute', difficulty: 'beginner', question: 'What is the difference between EC2 and Lambda?', answer: 'EC2: Virtual servers you manage, always running, pay per hour. Lambda: Serverless functions, run on-demand, pay per invocation, auto-scales to zero. Lambda ideal for event-driven, short tasks. EC2 for persistent workloads.', explanation: 'Lambda has 15min max execution, 10GB memory limit. EC2 gives full OS control. For web servers, EC2 or containers are typical. Lambda excels for async event processing, APIs with variable traffic.', tags: '["aws","lambda","ec2","serverless"]' },
  { channel: 'machine-learning', sub_channel: 'fundamentals', difficulty: 'beginner', question: 'What is the difference between supervised and unsupervised learning?', answer: 'Supervised: labeled training data, predicts output from input (classification, regression). Unsupervised: unlabeled data, finds patterns (clustering, dimensionality reduction). Semi-supervised combines both.', explanation: 'In supervised learning, the model learns a mapping from inputs to outputs using labeled examples. Unsupervised learning discovers hidden structure without guidance, useful for exploration and preprocessing.', tags: '["machine-learning","supervised","unsupervised"]' },
  { channel: 'security', sub_channel: 'web-security', difficulty: 'intermediate', question: 'What is OWASP Top 10? Name 3 critical vulnerabilities.', answer: 'OWASP Top 10 lists most critical web security risks. Key ones: 1) Injection (SQL, NoSQL) - untrusted data sent to interpreter. 2) Broken Authentication - weak credentials, session management. 3) XSS - malicious scripts injected into web pages.', explanation: 'Prevention: parameterized queries for injection, strong session management, Content Security Policy for XSS. Regular security audits against OWASP guidelines reduce attack surface significantly.', tags: '["security","OWASP","web-security","XSS"]' },
  { channel: 'behavioral', sub_channel: 'leadership', difficulty: 'beginner', question: 'Tell me about a time you had to make a difficult technical decision with incomplete information.', answer: 'Use STAR method: Situation (describe context), Task (your responsibility), Action (steps taken with rationale), Result (outcome and learnings). Show data-driven thinking, risk assessment, stakeholder communication, and adaptability.', explanation: 'Interviewers assess decision-making framework, risk tolerance, and ability to act under uncertainty. Good answers show systematic thinking, consultation with experts, and willingness to course-correct.', tags: '["behavioral","decision-making","leadership","STAR"]' },
];

async function seed() {
  let inserted = 0;
  const now = new Date().toISOString();
  for (const q of questions) {
    try {
      await client.execute({
        sql: `INSERT OR IGNORE INTO questions (id, question, answer, explanation, difficulty, channel, sub_channel, tags, status, last_updated, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, ?)`,
        args: [randomUUID(), q.question, q.answer, q.explanation, q.difficulty, q.channel, q.sub_channel, q.tags, now, now]
      });
      inserted++;
    } catch (e) {
      console.error('Error inserting:', q.question.slice(0, 50), e.message);
    }
  }
  
  const result = await client.execute('SELECT COUNT(*) as count FROM questions');
  console.log(`Seeded ${inserted} questions. Total in DB: ${result.rows[0].count}`);
}

seed().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
