/**
 * Issue #60 — Batch 5: More questions across all channels
 * Run: npx tsx scripts/seed-questions-batch5.ts
 */
import { createClient } from "@libsql/client";
import crypto from "crypto";

const client = createClient({ url: "file:local.db" });
const NOW = new Date().toISOString();
const id = () => crypto.randomUUID();

const questions = [
  // ── SYSTEM DESIGN ─────────────────────────────────────────────────────────
  {
    id: id(), channel: "system-design", subChannel: "scalability", difficulty: "advanced",
    question: "How would you design a URL shortener like bit.ly? Walk through the high-level design, data model, and key technical decisions.",
    answer: "Key components: (1) ID generation — base62 encoding of unique 7-char ID, (2) Storage — key-value store (Redis/DynamoDB) mapping shortCode→longURL, (3) Redirect service — 301 (cached) or 302 (analytics), (4) API service for creation, (5) Analytics: async via message queue. At scale: read-heavy (100:1 ratio), CDN + caching, global distribution. DB: DynamoDB for key-value lookups, analytical DB (Redshift/BigQuery) for click stats.",
    explanation: `## URL Shortener System Design\n\n### Requirements Clarification\n- Scale: 100M URLs created/day, 10B reads/day (100:1 read:write)\n- Latency: < 100ms redirect\n- URL expiry optional\n- Analytics: clicks by country, device, time\n\n### Data Model\n\`\`\`\nTable: short_urls\n- code: VARCHAR(8) PRIMARY KEY  # e.g., 'ab3X9yZ'\n- long_url: TEXT\n- user_id: UUID (nullable)\n- created_at: TIMESTAMP\n- expires_at: TIMESTAMP (nullable)\n- click_count: BIGINT\n\`\`\`\n\n### Short Code Generation\n**Base62 encoding**: characters [0-9, a-z, A-Z] = 62^7 = 3.5 trillion unique URLs\n\`\`\`python\nBASE62 = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'\ndef encode(num):\n    result = []\n    while num:\n        result.append(BASE62[num % 62])\n        num //= 62\n    return ''.join(reversed(result))\n\`\`\`\n\nID source: auto-increment counter (simpler) OR random ID with collision check.\n\n### Architecture\n\`\`\`\nClient → CDN (cache popular URLs) → Load Balancer\n       → Redirect Service → Redis (hot URLs cache, TTL=24h)\n                          → DynamoDB (all URLs, single-digit ms reads)\n       → Creation Service → ID Generator → DynamoDB write\n       → Message Queue (Kafka) → Analytics Consumer → Redshift\n\`\`\`\n\n### Key Decisions\n1. **301 vs 302 redirect**:\n   - 301 (Permanent): browser caches → no analytics after first visit. Best for performance.\n   - 302 (Temporary): every request hits our server → full analytics. Best for business.\n\n2. **Caching**: Top 20% URLs get 80% traffic. Cache in Redis with LRU eviction.\n\n3. **Custom aliases**: check availability, store with user's namespace.\n\n4. **Rate limiting**: prevent spam creation (10 URLs/minute/user).`,
    tags: JSON.stringify(["system-design", "url-shortener", "scalability", "design-interview"]),
  },
  {
    id: id(), channel: "system-design", subChannel: "real-time", difficulty: "advanced",
    question: "How would you design a real-time chat system like WhatsApp or Slack for millions of concurrent users?",
    answer: "Key challenges: real-time message delivery, offline storage, presence (online/offline), group chats, media. WebSocket connections to chat servers (stateful). Message delivery: producer→Kafka→consumer per user connection. Offline: store in Cassandra (time-series), push notifications (APNs/FCM). Fan-out for group chats: write to each member's mailbox or inbox pull pattern. Media: upload to S3, store URL.",
    explanation: `## Real-Time Chat System Design\n\n### Core Challenges\n1. Real-time delivery (WebSocket or long-polling)\n2. Message persistence + offline delivery\n3. Online presence (who's online?)\n4. Group chat fan-out (1 message → N users)\n5. Media/file sharing\n6. End-to-end encryption\n\n### Architecture\n\n#### Message Flow\n\`\`\`\nSender → WebSocket → Chat Server A → Kafka topic per user → Chat Server B → WebSocket → Receiver\n                                    → Message DB (Cassandra)\n                                    → Notification Service (if receiver offline) → APNs/FCM\n\`\`\`\n\n#### Data Model (Cassandra — time-series)\n\`\`\`\n-- Conversation messages, partitioned for efficient time-range queries\nCREATE TABLE messages (\n  conversation_id UUID,\n  message_id TIMEUUID,  -- time-based UUID for ordering\n  sender_id UUID,\n  content TEXT,\n  media_url TEXT,\n  PRIMARY KEY (conversation_id, message_id)\n) WITH CLUSTERING ORDER BY (message_id DESC);\n\`\`\`\n\n### Presence System\n- User connects → publish to Redis (user_id → server_id, TTL=30s)\n- Heartbeat every 20s resets TTL\n- User disconnects → TTL expires → offline\n- Subscribe to presence channel for contacts\n\n### Group Chat Fan-out Strategies\n1. **Push**: when message sent, write to each member's inbox (simple, expensive for huge groups)\n2. **Pull**: message stored once, clients pull at read time (efficient, complex)\n3. **Hybrid**: push for small groups (< 1000), pull for large channels\n\n### Scale Numbers\n- 50M daily active users\n- 50 WebSocket connections per chat server → 1M users = 20k servers\n- Use consistent hashing to assign users to servers\n- Chat servers are stateless-ish (store session in Redis)`,
    tags: JSON.stringify(["system-design", "chat", "websocket", "real-time", "kafka"]),
  },
  {
    id: id(), channel: "system-design", subChannel: "databases", difficulty: "intermediate",
    question: "When would you choose a SQL (relational) database vs a NoSQL database? What are the trade-offs?",
    answer: "SQL: ACID transactions, complex queries with JOINs, strong consistency, structured schema. Best for: financial systems, e-commerce orders, user accounts. NoSQL types: Document (MongoDB — flexible schema), Key-Value (Redis/DynamoDB — ultra-fast simple lookups), Column (Cassandra — time-series, append-heavy), Graph (Neo4j — relationships). Best for: high scale with simple access patterns, flexible/evolving schema, horizontal scaling.",
    explanation: `## SQL vs NoSQL Trade-offs\n\n### SQL Databases\n**Examples**: PostgreSQL, MySQL, SQLite, Amazon RDS\n\n**Strengths**:\n- ACID transactions (critical for financial data)\n- Complex queries (JOINs, GROUP BY, subqueries)\n- Strong consistency\n- Mature ecosystem, battle-tested\n- Schema enforcement (data integrity)\n\n**Weaknesses**:\n- Vertical scaling mostly (horizontal = sharding, complex)\n- Schema migrations require care\n- ORM overhead for complex access patterns\n\n### NoSQL Databases\n| Type | Examples | Best For |\n|------|----------|----------|\n| Document | MongoDB, Firestore | Flexible schema, nested documents |\n| Key-Value | Redis, DynamoDB | Simple lookups, caching, sessions |\n| Wide Column | Cassandra, HBase | Time-series, IoT, append-heavy |\n| Graph | Neo4j, Amazon Neptune | Social graphs, recommendation engines |\n\n**Strengths**:\n- Horizontal scaling (built-in sharding)\n- Flexible schema (evolving data models)\n- Optimized for specific access patterns\n- Often higher throughput for simple queries\n\n**Weaknesses**:\n- Eventual consistency (mostly)\n- Limited JOIN capabilities\n- Weaker transaction support (improving)\n\n### Decision Framework\n- Need ACID + complex queries → SQL\n- Need extreme scale + simple access → NoSQL\n- Need both? → Polyglot persistence (different DBs for different parts)\n\n**Real Example**: Uber uses MySQL for core business, Cassandra for trip history, Redis for driver location.`,
    tags: JSON.stringify(["system-design", "databases", "sql", "nosql", "trade-offs"]),
  },

  // ── ALGORITHMS EXTRA ──────────────────────────────────────────────────────
  {
    id: id(), channel: "algorithms", subChannel: "dynamic-programming", difficulty: "advanced",
    question: "What is dynamic programming? How do you recognize a DP problem? Explain with the Fibonacci and Coin Change examples.",
    answer: "Dynamic Programming: break problem into overlapping subproblems, solve each once, store results (memoization/tabulation). Recognize DP by: optimal substructure (optimal solution uses optimal solutions of subproblems) + overlapping subproblems. Fibonacci: memo[n] = memo[n-1] + memo[n-2]. Coin Change: min coins to make amount = 1 + min(subproblems for each coin). Time: O(n*k) instead of exponential.",
    explanation: `## Dynamic Programming\n\n### Two Key Properties\n1. **Optimal Substructure**: optimal solution to problem contains optimal solutions to subproblems\n2. **Overlapping Subproblems**: same subproblems computed multiple times in naive recursion\n\n### Fibonacci — Classic DP\n\`\`\`python\n# Naive recursion: O(2^n)\ndef fib(n):\n    if n <= 1: return n\n    return fib(n-1) + fib(n-2)  # recomputes fib(n-2) many times!\n\n# Top-down memoization: O(n)\nfrom functools import lru_cache\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n <= 1: return n\n    return fib(n-1) + fib(n-2)\n\n# Bottom-up tabulation: O(n) time, O(1) space\ndef fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\`\`\`\n\n### Coin Change — DP\n\`\`\`python\ndef coinChange(coins, amount):\n    # dp[i] = minimum coins to make amount i\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0  # 0 coins to make amount 0\n    \n    for i in range(1, amount + 1):\n        for coin in coins:\n            if coin <= i:\n                dp[i] = min(dp[i], dp[i - coin] + 1)\n    \n    return dp[amount] if dp[amount] != float('inf') else -1\n# Time: O(amount * len(coins)), Space: O(amount)\n\`\`\`\n\n### How to Recognize DP Problems\n- "minimum/maximum number of..."\n- "count the ways to..."\n- "can we reach..."\n- "longest/shortest sequence..."\n- Choices at each step with consequences\n\n### DP vs Greedy\nDP: considers ALL options and picks best. Greedy: picks locally best option. DP is more general but more complex.`,
    tags: JSON.stringify(["algorithms", "dynamic-programming", "memoization", "fibonacci", "coin-change"]),
  },
  {
    id: id(), channel: "algorithms", subChannel: "graphs", difficulty: "advanced",
    question: "Explain Dijkstra's algorithm. What is its time complexity and when does it fail?",
    answer: "Dijkstra finds the shortest path from a source to all vertices in a weighted graph. Uses a min-heap (priority queue). Greedily picks the unvisited vertex with smallest known distance, relaxes its neighbors. Time: O((V+E) log V) with binary heap. FAILS with negative edge weights (use Bellman-Ford instead). FAILS to detect negative cycles. Use cases: GPS routing, network routing, game AI pathfinding.",
    explanation: `## Dijkstra's Algorithm\n\n### Algorithm\n\`\`\`python\nimport heapq\n\ndef dijkstra(graph, source):\n    # graph: adjacency list {node: [(neighbor, weight), ...]}\n    dist = {node: float('inf') for node in graph}\n    dist[source] = 0\n    heap = [(0, source)]  # (distance, node)\n    visited = set()\n    \n    while heap:\n        d, u = heapq.heappop(heap)\n        if u in visited:\n            continue\n        visited.add(u)\n        \n        for v, weight in graph[u]:\n            if d + weight < dist[v]:\n                dist[v] = d + weight\n                heapq.heappush(heap, (dist[v], v))\n    \n    return dist\n\`\`\`\n\n### Example\n\`\`\`\nGraph: A-B(4), A-C(2), C-B(1), B-D(5), C-D(8)\nSource: A\n\nStep 1: Pick A (dist=0). Update: B=4, C=2\nStep 2: Pick C (dist=2). Update: B=min(4,2+1)=3, D=2+8=10\nStep 3: Pick B (dist=3). Update: D=min(10,3+5)=8\nStep 4: Pick D (dist=8). Done.\n\nResult: A=0, B=3, C=2, D=8\n\`\`\`\n\n### Time Complexity\n- Binary Heap: **O((V + E) log V)**\n- Fibonacci Heap: O(V log V + E) — theoretically better, complex to implement\n- Without heap (arrays): O(V²) — better for dense graphs\n\n### Limitations\n- **Fails with negative weights**: greedy assumption (once visited, shortest path found) breaks. Use Bellman-Ford O(VE) or SPFA.\n- **Fails with negative cycles**: use Bellman-Ford (detects negative cycles).\n\n### Real Applications\n- GPS routing: road network as weighted graph\n- OSPF network routing protocol\n- A* pathfinding (Dijkstra + heuristic)`,
    tags: JSON.stringify(["algorithms", "graphs", "dijkstra", "shortest-path", "priority-queue"]),
  },

  // ── BACKEND EXTRA ─────────────────────────────────────────────────────────
  {
    id: id(), channel: "backend", subChannel: "api-design", difficulty: "intermediate",
    question: "What is REST? What are its constraints and what makes a good RESTful API?",
    answer: "REST (Representational State Transfer): architectural style with 6 constraints — stateless (no server-side session), uniform interface (standard HTTP methods + nouns), client-server separation, cacheable, layered system, code on demand (optional). Good REST API: uses HTTP verbs correctly (GET/POST/PUT/PATCH/DELETE), nouns not verbs in URLs (/users not /getUsers), proper status codes, versioning (/v1/), consistent error format, pagination for collections.",
    explanation: `## REST API Design\n\n### 6 REST Constraints\n1. **Stateless**: each request contains all info needed. No server session. Auth via token in header.\n2. **Uniform Interface**: consistent resource identification (URLs), HTTP methods, representation (JSON)\n3. **Client-Server**: separation of concerns — client handles UI, server handles data\n4. **Cacheable**: responses indicate cacheability (Cache-Control headers)\n5. **Layered System**: client doesn't know if it's talking to backend, CDN, or proxy\n6. **Code on Demand** (optional): server can send executable code (JavaScript) to client\n\n### HTTP Verb Semantics\n| Verb | Use | Idempotent? | Safe? |\n|------|-----|-------------|-------|\n| GET | Read | Yes | Yes |\n| POST | Create | No | No |\n| PUT | Full replace | Yes | No |\n| PATCH | Partial update | No | No |\n| DELETE | Delete | Yes | No |\n\n### URL Design Best Practices\n\`\`\`\n# GOOD — nouns, hierarchical, plural\nGET    /v1/users              # list all users\nPOST   /v1/users              # create user\nGET    /v1/users/{id}         # get user\nPUT    /v1/users/{id}         # replace user\nPATCH  /v1/users/{id}         # update user fields\nDELETE /v1/users/{id}         # delete user\nGET    /v1/users/{id}/orders  # user's orders\n\n# BAD — verbs in URL, inconsistent\nGET /getUser?id=123\nPOST /createNewUser\nGET /user-orders/{userId}\n\`\`\`\n\n### Status Codes\n- 200 OK, 201 Created, 204 No Content\n- 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 409 Conflict, 422 Unprocessable\n- 500 Internal Server Error, 503 Service Unavailable\n\n### Error Response Format\n\`\`\`json\n{\n  "error": {\n    "code": "VALIDATION_ERROR",\n    "message": "Email is required",\n    "fields": [{"field": "email", "message": "Required"}]\n  }\n}\n\`\`\``,
    tags: JSON.stringify(["backend", "rest", "api-design", "http", "web-development"]),
  },
  {
    id: id(), channel: "backend", subChannel: "caching", difficulty: "intermediate",
    question: "What are the different caching strategies (write-through, write-around, write-back)? When do you use each?",
    answer: "Write-through: write to cache AND DB simultaneously — cache always consistent, but write latency doubled. Write-around: write directly to DB, bypassing cache — good for infrequently re-read data. Write-back (write-behind): write to cache only, async write to DB — fastest writes, risk of data loss if cache fails. Read-through: cache handles DB reads automatically. Cache-aside (lazy loading): app code checks cache, populates on miss — most flexible.",
    explanation: `## Caching Strategies\n\n### Cache-Aside (Lazy Loading) — Most Common\n\`\`\`python\ndef get_user(user_id):\n    # Check cache first\n    user = redis.get(f'user:{user_id}')\n    if user:\n        return json.loads(user)  # Cache hit!\n    \n    # Cache miss — fetch from DB\n    user = db.query('SELECT * FROM users WHERE id = ?', user_id)\n    redis.setex(f'user:{user_id}', 3600, json.dumps(user))  # Cache for 1 hour\n    return user\n\`\`\`\n**Pros**: Only cache what's needed. **Cons**: First request always slow (cold start). Risk: stale data on DB update.\n\n### Write-Through\n\`\`\`python\ndef update_user(user_id, data):\n    db.update('users', user_id, data)      # Update DB\n    redis.set(f'user:{user_id}', data)     # Update cache simultaneously\n\`\`\`\n**Pros**: Cache always in sync. **Cons**: Write latency doubled. Cache may have rarely-read data.\n\n### Write-Back (Write-Behind)\n\`\`\`python\ndef update_user(user_id, data):\n    redis.set(f'user:{user_id}', data)     # Update cache only\n    queue.push({'user_id': user_id, 'data': data})  # Async write to DB\n\`\`\`\n**Pros**: Lowest write latency. **Cons**: Risk of data loss if Redis fails before async write completes. Good for analytics counters.\n\n### Write-Around\nWrite directly to DB, don't update cache. Next read will be a cache miss.\n**Use when**: Data written once but rarely read (audit logs, historical data).\n\n### Summary\n| Strategy | Write Speed | Read Speed | Consistency | Data Loss Risk |\n|----------|------------|-----------|-------------|---------------|\n| Cache-aside | DB speed | Cache speed | Moderate | None |\n| Write-through | Slow (2x) | Cache speed | Strong | None |\n| Write-back | Cache speed | Cache speed | Eventual | Yes |\n| Write-around | DB speed | First = slow | Strong | None |`,
    tags: JSON.stringify(["backend", "caching", "redis", "performance", "write-through"]),
  },

  // ── FRONTEND EXTRA ────────────────────────────────────────────────────────
  {
    id: id(), channel: "frontend", subChannel: "performance", difficulty: "intermediate",
    question: "What are Core Web Vitals and how do you optimize for them?",
    answer: "Core Web Vitals are Google's UX metrics: LCP (Largest Contentful Paint, < 2.5s) = loading speed of main content, FID/INP (Interaction to Next Paint, < 200ms) = input responsiveness, CLS (Cumulative Layout Shift, < 0.1) = visual stability. Optimize LCP: preload hero image, server-side render, CDN. Optimize INP: break up long tasks (< 50ms), requestIdleCallback, web workers. Optimize CLS: set width/height on images/videos, avoid injecting content above fold.",
    explanation: `## Core Web Vitals\n\n### LCP (Largest Contentful Paint) — Target: < 2.5s\nMeasures loading performance of the largest visible element.\n\n**Common LCP elements**: hero images, h1 headings, video thumbnails.\n\n**Optimizations**:\n\`\`\`html\n<!-- Preload LCP image -->\n<link rel="preload" as="image" href="/hero.webp" />\n\n<!-- Add dimensions to prevent layout shifts + load early -->\n<img src="/hero.webp" width="800" height="400" fetchpriority="high" />\n\`\`\`\n- Use CDN for images (CloudFront, Cloudflare)\n- Compress images: WebP (26% smaller than JPEG)\n- SSR/SSG for HTML content as LCP element\n- Reduce TTFB (Time to First Byte) with edge caching\n\n### INP (Interaction to Next Paint) — Target: < 200ms\nMeasures responsiveness of the page to user interactions.\n\n**Optimizations**:\n\`\`\`javascript\n// Break up long tasks\nfunction processLargeArray(items) {\n    const CHUNK_SIZE = 100;\n    let i = 0;\n    function processChunk() {\n        items.slice(i, i + CHUNK_SIZE).forEach(process);\n        i += CHUNK_SIZE;\n        if (i < items.length) setTimeout(processChunk, 0); // yield to browser\n    }\n    processChunk();\n}\n\n// Move heavy computation off main thread\nconst worker = new Worker('sort-worker.js');\nworker.postMessage({ data: largeDataset });\n\`\`\`\n\n### CLS (Cumulative Layout Shift) — Target: < 0.1\nMeasures unexpected layout shifts.\n\n**Optimizations**:\n\`\`\`css\n/* Always set dimensions on media */\nimg { aspect-ratio: 16/9; width: 100%; }\n\n/* Reserve space for dynamic content */\n.ad-slot { min-height: 250px; }\n\`\`\`\n- Don't inject content above existing content\n- Use CSS animations (transform/opacity) not layout-changing props\n- Font display: swap with size-adjust to prevent FOUT layout shifts`,
    tags: JSON.stringify(["frontend", "performance", "core-web-vitals", "lcp", "cls", "inp"]),
  },

  // ── DATABASE EXTRA ────────────────────────────────────────────────────────
  {
    id: id(), channel: "database", subChannel: "query-optimization", difficulty: "advanced",
    question: "How do you optimize a slow SQL query? What tools and techniques do you use?",
    answer: "Step 1: EXPLAIN ANALYZE to see query plan. Look for: Sequential Scans (add index), Hash Joins on large tables, high actual rows vs estimated rows (stale statistics → ANALYZE). Step 2: Add missing indexes on WHERE, JOIN, ORDER BY columns. Step 3: Avoid SELECT *, use covering indexes. Step 4: Rewrite correlated subqueries as JOINs. Step 5: Partition large tables. Step 6: Denormalize hot query paths. Step 7: Add read replicas for read-heavy workloads.",
    explanation: `## SQL Query Optimization\n\n### Step 1: Understand the Query Plan\n\`\`\`sql\nEXPLAIN ANALYZE\nSELECT o.*, u.email\nFROM orders o\nJOIN users u ON o.user_id = u.id\nWHERE o.status = 'pending'\nORDER BY o.created_at DESC\nLIMIT 20;\n\`\`\`\n\n**Reading EXPLAIN output**:\n- \`Seq Scan\` on large table = missing index\n- \`rows=10000\` but \`actual rows=5\` = stale statistics (run ANALYZE)\n- \`Hash Join\` cost > 1000 = consider index\n- Loops × rows = actual work done\n\n### Step 2: Add Targeted Indexes\n\`\`\`sql\n-- Bad: index on single column when query filters on two\nCREATE INDEX idx_orders_status ON orders(status);\n\n-- Better: composite index matches query\nCREATE INDEX idx_orders_status_date ON orders(status, created_at DESC);\n\n-- Covering index: includes all selected columns (no table heap access)\nCREATE INDEX idx_orders_covering ON orders(status, created_at DESC)\nINCLUDE (user_id, total_amount);\n\`\`\`\n\n### Step 3: Rewrite Correlated Subqueries\n\`\`\`sql\n-- Slow: correlated subquery runs for every row\nSELECT u.*, (\n    SELECT COUNT(*) FROM orders WHERE user_id = u.id\n) as order_count\nFROM users u;\n\n-- Fast: single join + aggregate\nSELECT u.*, COALESCE(o.cnt, 0) as order_count\nFROM users u\nLEFT JOIN (\n    SELECT user_id, COUNT(*) as cnt\n    FROM orders\n    GROUP BY user_id\n) o ON u.id = o.user_id;\n\`\`\`\n\n### Other Techniques\n- **Pagination**: use \`WHERE id > last_seen_id LIMIT 20\` (keyset) instead of \`OFFSET 10000\` (slow)\n- **Partitioning**: partition large tables by date — queries only scan relevant partition\n- **Materialized views**: pre-compute expensive aggregations\n- **Update statistics**: \`VACUUM ANALYZE\` in PostgreSQL regularly\n- **Connection pooling**: PgBouncer for PostgreSQL`,
    tags: JSON.stringify(["database", "query-optimization", "sql", "explain", "indexing", "performance"]),
  },

  // ── KUBERNETES EXTRA ──────────────────────────────────────────────────────
  {
    id: id(), channel: "kubernetes", subChannel: "rbac", difficulty: "advanced",
    question: "What is RBAC in Kubernetes? Explain Roles, ClusterRoles, RoleBindings, and ClusterRoleBindings.",
    answer: "RBAC (Role-Based Access Control): controls what K8s API operations (verbs) a user/service account can perform on which resources. Role: namespace-scoped permissions. ClusterRole: cluster-wide permissions (also for cluster-scoped resources like Nodes). RoleBinding: grants a Role to a user within a namespace. ClusterRoleBinding: grants ClusterRole cluster-wide. Always use principle of least privilege.",
    explanation: `## Kubernetes RBAC\n\n### Components\n\n#### Role (Namespace-Scoped)\n\`\`\`yaml\napiVersion: rbac.authorization.k8s.io/v1\nkind: Role\nmetadata:\n  name: pod-reader\n  namespace: development\nrules:\n- apiGroups: [""]          # "" = core API group\n  resources: ["pods", "pods/log"]\n  verbs: ["get", "list", "watch"]  # read-only\n\`\`\`\n\n#### ClusterRole (Cluster-Wide)\n\`\`\`yaml\napiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole\nmetadata:\n  name: node-reader\nrules:\n- apiGroups: [""]\n  resources: ["nodes"]      # cluster-scoped, can't use Role\n  verbs: ["get", "list"]\n\`\`\`\n\n#### RoleBinding (Bind Role to User in Namespace)\n\`\`\`yaml\napiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding\nmetadata:\n  name: read-pods\n  namespace: development\nsubjects:\n- kind: User\n  name: alice                    # developer\n- kind: ServiceAccount\n  name: ci-bot\n  namespace: ci\nroleRef:\n  kind: Role\n  name: pod-reader\n  apiGroup: rbac.authorization.k8s.io\n\`\`\`\n\n### Common Verbs\n| Verb | REST Equiv | Description |\n|------|-----------|-------------|\n| get | GET /resource/name | Read one |\n| list | GET /resource | List all |\n| watch | GET /resource?watch=true | Stream changes |\n| create | POST | Create |\n| update | PUT | Replace |\n| patch | PATCH | Partial update |\n| delete | DELETE | Delete |\n\n### Debugging RBAC\n\`\`\`bash\n# Can Alice list pods in development?\nkubectl auth can-i list pods -n development --as alice\n\n# What can the ci-bot service account do?\nkubectl auth can-i --list --as=system:serviceaccount:ci:ci-bot\n\`\`\``,
    tags: JSON.stringify(["kubernetes", "rbac", "security", "authorization", "service-accounts"]),
  },

  // ── ALGORITHMS EXTRA ──────────────────────────────────────────────────────
  {
    id: id(), channel: "algorithms", subChannel: "sorting", difficulty: "intermediate",
    question: "Compare merge sort and quicksort. When would you use each?",
    answer: "Merge sort: always O(n log n), stable sort, O(n) extra space, good for linked lists and external sorting. Quicksort: O(n log n) average, O(n²) worst case (avoided with random pivot), in-place O(log n) space, excellent cache performance, faster in practice for arrays. Use merge sort when stability needed or external data. Use quicksort for in-memory arrays (most standard library sort implementations use introsort = quicksort + heapsort hybrid).",
    explanation: `## Merge Sort vs Quicksort\n\n### Merge Sort\n\`\`\`python\ndef merge_sort(arr):\n    if len(arr) <= 1: return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:  # <= preserves stability\n            result.append(left[i]); i += 1\n        else:\n            result.append(right[j]); j += 1\n    return result + left[i:] + right[j:]\n\`\`\`\n**Properties**: Always O(n log n), Stable, O(n) extra space\n\n### Quicksort\n\`\`\`python\ndef quicksort(arr, lo=0, hi=None):\n    if hi is None: hi = len(arr) - 1\n    if lo < hi:\n        pivot = partition(arr, lo, hi)\n        quicksort(arr, lo, pivot - 1)\n        quicksort(arr, pivot + 1, hi)\n\ndef partition(arr, lo, hi):\n    import random\n    rand = random.randint(lo, hi)\n    arr[rand], arr[hi] = arr[hi], arr[rand]  # random pivot\n    pivot = arr[hi]\n    i = lo - 1\n    for j in range(lo, hi):\n        if arr[j] <= pivot:\n            i += 1\n            arr[i], arr[j] = arr[j], arr[i]\n    arr[i+1], arr[hi] = arr[hi], arr[i+1]\n    return i + 1\n\`\`\`\n**Properties**: O(n log n) avg, O(n²) worst (random pivot avoids), In-place\n\n### Comparison\n| | Merge Sort | Quicksort |\n|--|-----------|----------|\n| Time (avg) | O(n log n) | O(n log n) |\n| Time (worst) | O(n log n) | O(n²) |\n| Space | O(n) | O(log n) |\n| Stable | Yes | No |\n| Cache | Poor (non-contiguous) | Excellent |\n| Use for | Linked lists, external sort | Arrays (default) |`,
    tags: JSON.stringify(["algorithms", "sorting", "merge-sort", "quicksort", "comparison"]),
  },
];

async function main() {
  console.log(`Seeding ${questions.length} questions (system-design, algorithms, backend, frontend, database, kubernetes)...`);
  let count = 0;
  for (const q of questions) {
    await client.execute({
      sql: `INSERT OR IGNORE INTO questions
        (id, question, answer, explanation, difficulty, tags, channel, sub_channel, status, is_new, created_at, last_updated)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,
      args: [q.id, q.question, q.answer, q.explanation, q.difficulty, q.tags, q.channel, q.subChannel, "active", 1, NOW, NOW],
    });
    count++;
    console.log(`[${q.channel}/${q.subChannel}] ${q.question.slice(0, 55).replace(/\n/g, " ")}...`);
  }
  console.log(`\nDone! ${count} questions inserted.`);
  client.close();
}
main().catch((e) => { console.error(e); process.exit(1); });
