/**
 * Issue #60 — Batch 3: Data structures, TypeScript, Node.js, networking, kubernetes deep dives
 * Run: npx tsx scripts/seed-questions-batch3.ts
 */
import { createClient } from "@libsql/client";
import crypto from "crypto";

const client = createClient({ url: "file:local.db" });
const NOW = new Date().toISOString();
const id = () => crypto.randomUUID();

const questions = [
  // ── DATA STRUCTURES ───────────────────────────────────────────────────────
  {
    id: id(), channel: "data-structures", subChannel: "trees", difficulty: "intermediate",
    question: "What is a Binary Search Tree (BST)? What are the time complexities for search, insert, and delete operations?",
    answer: "A BST is a binary tree where left subtree values < node value < right subtree values. Average case: O(log n) for search/insert/delete. Worst case (degenerate/unbalanced tree): O(n). Balanced BSTs (AVL, Red-Black Trees) guarantee O(log n) worst case.",
    explanation: `## Binary Search Tree\n\n### Properties\n- Left subtree: all values < node\n- Right subtree: all values > node\n- Each subtree is also a BST\n\n### Operations\n\`\`\`python\nclass BST:\n    def search(self, root, val):\n        if not root or root.val == val: return root\n        if val < root.val: return self.search(root.left, val)\n        return self.search(root.right, val)\n    \n    def insert(self, root, val):\n        if not root: return TreeNode(val)\n        if val < root.val: root.left = self.insert(root.left, val)\n        else: root.right = self.insert(root.right, val)\n        return root\n\`\`\`\n\n### Complexity\n| Operation | Average | Worst (unbalanced) |\n|-----------|---------|--------------------|\n| Search | O(log n) | O(n) |\n| Insert | O(log n) | O(n) |\n| Delete | O(log n) | O(n) |\n\n### Worst Case Example\n```\nInsert 1, 2, 3, 4, 5 in order:\n1\n \\  2\n    \\  3\n        \\  4  ← Degenerate tree = linked list\n```\n\n### Self-Balancing BSTs\n- **AVL Tree**: Height difference ≤ 1. O(log n) guaranteed.\n- **Red-Black Tree**: Used in C++ std::map, Java TreeMap\n- **B-Tree**: Used in database indexes`,
    eli5: "A BST is like a sorted filing system where smaller items go left and bigger items go right. Finding something is fast when the tree is balanced — like a proper pyramid. But if you add items in order, it becomes a leaning tower and slows way down.",
    tags: JSON.stringify(["data-structures", "trees", "bst", "binary-search-tree"]),
  },
  {
    id: id(), channel: "data-structures", subChannel: "heaps", difficulty: "intermediate",
    question: "What is a heap, how is a min-heap maintained, and what problem does it solve most efficiently?",
    answer: "A heap is a complete binary tree satisfying the heap property. Min-heap: parent ≤ children (root = minimum). Maintained by 'heapify-up' on insert and 'heapify-down' on extract. Best for: finding/extracting min/max in O(log n), priority queues, Dijkstra's algorithm, and finding the k-th largest element in O(n log k).",
    explanation: `## Heap Data Structure\n\n### Min-Heap Property\nParent ≤ children at every node. Root is always the minimum.\n\n### Stored as Array\n\`\`\`\nHeap: [1, 3, 6, 5, 9, 8]\nParent of i: (i-1) // 2\nLeft child: 2*i + 1\nRight child: 2*i + 2\n\`\`\`\n\n### Insert (Heapify-Up)\n\`\`\`python\ndef push(heap, val):\n    heap.append(val)\n    i = len(heap) - 1\n    while i > 0:\n        parent = (i - 1) // 2\n        if heap[parent] > heap[i]:\n            heap[parent], heap[i] = heap[i], heap[parent]\n            i = parent\n        else: break\n\`\`\`\n\n### Extract-Min (Heapify-Down)\n\`\`\`python\nimport heapq\n# Python's heapq is a min-heap\nheap = []\nheapq.heappush(heap, 3)\nheapq.heappush(heap, 1)\nheapq.heappush(heap, 2)\nprint(heapq.heappop(heap))  # 1 (minimum)\n\`\`\`\n\n### Complexity\n| Operation | Time |\n|-----------|------|\n| Push | O(log n) |\n| Pop min | O(log n) |\n| Peek min | O(1) |\n| Build heap | O(n) |\n\n### Classic Problems\n- **K largest elements**: Push all, maintain size-k min-heap → O(n log k)\n- **Merge k sorted lists**: Use min-heap of (value, list_index)\n- **Median of stream**: Two heaps (max-heap for lower half, min-heap for upper half)`,
    eli5: "A min-heap is like a tournament bracket where the smallest number always bubbles up to the top. You can always instantly see (and remove) the smallest number, and putting in a new number is fast because it only needs to move up to its correct level.",
    tags: JSON.stringify(["data-structures", "heaps", "priority-queue", "min-heap"]),
  },
  {
    id: id(), channel: "data-structures", subChannel: "linked-lists", difficulty: "beginner",
    question: "When would you use a linked list over an array, and what are the trade-offs?",
    answer: "Linked lists excel at O(1) insertions/deletions at head (no shifting needed). Arrays excel at O(1) random access by index. Linked lists use more memory (pointer per node) and have poor cache locality. Use linked lists for: frequent front insertions (queues), unknown size, or when avoiding shifting elements matters more than random access.",
    explanation: `## Linked List vs Array\n\n### Array\n\`\`\`\nMemory: [1][2][3][4][5]  ← contiguous\nAccess arr[3] = O(1) (direct address calculation)\nInsert middle: O(n) — must shift all elements right\n\`\`\`\n\n### Linked List\n\`\`\`\n[1]→[2]→[3]→[4]→[5]→null  ← scattered in memory\nAccess node[3]: O(n) — must traverse from head\nInsert at head: O(1) — just update pointers\n\`\`\`\n\n### Comparison\n| Operation | Array | Linked List |\n|-----------|-------|-------------|\n| Access by index | O(1) | O(n) |\n| Insert at head | O(n) | O(1) |\n| Insert at tail | O(1) amortized | O(1) if tail ptr |\n| Insert at middle | O(n) | O(n) search + O(1) insert |\n| Delete at head | O(n) | O(1) |\n| Space overhead | None | 8 bytes/node (pointer) |\n| Cache locality | Excellent | Poor |\n\n### Real Use Cases\n- **LinkedList**: Browser history (back/forward), undo/redo, LRU cache implementation\n- **Array**: Sorting, binary search, most general use, matrix operations\n\n### Common Interview Tricks\n- Detect cycle: Floyd's tortoise and hare (slow/fast pointer)\n- Find middle: Two pointers (slow advances 1, fast advances 2)\n- Reverse in-place: Three pointers (prev, curr, next)`,
    eli5: "An array is like numbered lockers — you can instantly go to locker 42. A linked list is like a treasure hunt — each clue points to the next. Arrays are faster for finding things; linked lists are faster for adding or removing from the front.",
    tags: JSON.stringify(["data-structures", "linked-lists", "arrays", "trade-offs"]),
  },
  {
    id: id(), channel: "data-structures", subChannel: "graphs", difficulty: "intermediate",
    question: "How do you detect a cycle in a directed graph vs an undirected graph?",
    answer: "Directed graph: DFS with three states — white (unvisited), gray (in current path), black (fully visited). If you reach a gray node → cycle detected. Undirected graph: DFS and track parent. If you reach a visited node that isn't the current parent → cycle. Can also use Union-Find (disjoint set) for undirected cycles.",
    explanation: `## Cycle Detection\n\n### Directed Graph — DFS with Colors\n- White: not visited\n- Gray: in current DFS path (recursion stack)\n- Black: fully processed\n\nCycle exists if we reach a GRAY node (back edge in DFS).\n\n\`\`\`python\ndef has_cycle_directed(graph, n):\n    color = [0] * n  # 0=white, 1=gray, 2=black\n    \n    def dfs(node):\n        color[node] = 1  # Gray\n        for neighbor in graph[node]:\n            if color[neighbor] == 1:  # Gray → back edge → cycle!\n                return True\n            if color[neighbor] == 0 and dfs(neighbor):\n                return True\n        color[node] = 2  # Black\n        return False\n    \n    return any(dfs(i) for i in range(n) if color[i] == 0)\n\`\`\`\n\n### Undirected Graph — DFS with Parent Tracking\n\`\`\`python\ndef has_cycle_undirected(graph, n):\n    visited = [False] * n\n    \n    def dfs(node, parent):\n        visited[node] = True\n        for neighbor in graph[node]:\n            if not visited[neighbor]:\n                if dfs(neighbor, node): return True\n            elif neighbor != parent:  # Visited and not parent → cycle!\n                return True\n        return False\n    \n    return any(dfs(i, -1) for i in range(n) if not visited[i])\n\`\`\`\n\n### Union-Find for Undirected\nFor each edge (u, v), if find(u) == find(v) → cycle. Otherwise union(u, v).\n\n### Complexity\nBoth: O(V + E) time, O(V) space`,
    eli5: "Detecting a cycle in a graph is like checking if you can get lost on a trail that brings you back to where you started. In a one-way street network, you look for any road that takes you back to a road you're currently on. In a two-way network, you just check if any connection leads back without retracing your exact steps.",
    tags: JSON.stringify(["data-structures", "graphs", "cycle-detection", "dfs"]),
  },

  // ── TYPESCRIPT ────────────────────────────────────────────────────────────
  {
    id: id(), channel: "frontend", subChannel: "typescript", difficulty: "intermediate",
    question: "What is the difference between 'interface' and 'type' in TypeScript? When should you use each?",
    answer: "Both define type shapes but have differences: Interfaces support declaration merging (re-declaring adds properties) and are slightly better for OOP/class contracts. Type aliases support union types, intersection types, and computed types. In practice: use interface for objects/class shapes and API contracts; use type for unions, intersections, and computed/utility types.",
    explanation: `## TypeScript: interface vs type\n\n### interface\n\`\`\`typescript\ninterface User {\n  id: number;\n  name: string;\n}\n\n// Declaration merging (unique to interface)\ninterface User {\n  email: string;  // Merged! User now has id + name + email\n}\n\n// Class implementation\nclass Admin implements User {\n  id = 1; name = "Admin"; email = "admin@co.com";\n}\n\`\`\`\n\n### type alias\n\`\`\`typescript\ntype User = {\n  id: number;\n  name: string;\n};\n\n// Can't be re-declared (unlike interface)\n\n// Only type can do union types\ntype Status = "active" | "inactive" | "pending";\n\n// Only type can do computed types\ntype UserKeys = keyof User;  // "id" | "name"\n\n// Intersection\ntype AdminUser = User & { role: "admin" };\n\`\`\`\n\n### Key Differences\n| Feature | interface | type |\n|---------|----------|------|\n| Union types | ❌ | ✅ |\n| Declaration merging | ✅ | ❌ |\n| Extends | extends keyword | & (intersection) |\n| Class implements | ✅ | ✅ (object shape only) |\n| Utility types | Both work equally well |\n\n### Recommendation\n- **interface**: Object shapes, class contracts, library APIs\n- **type**: Unions, intersections, utility types, aliases for primitives`,
    eli5: "Both interface and type are ways to describe the shape of data in TypeScript. Interface is like a contract for objects and classes — it can even be extended later. Type is more flexible — it can describe unions (this OR that) which interface can't do.",
    tags: JSON.stringify(["frontend", "typescript", "interface", "type-alias"]),
  },
  {
    id: id(), channel: "frontend", subChannel: "typescript", difficulty: "advanced",
    question: "What are TypeScript generics and what problem do they solve? Show an example with a generic function.",
    answer: "Generics allow writing type-safe functions/classes that work with any type without losing type information. Without generics, you'd use 'any' (losing type safety) or write separate functions for each type. With generics, you write one function and TypeScript infers or checks the type at each call site.",
    explanation: `## TypeScript Generics\n\n### Problem Without Generics\n\`\`\`typescript\n// Option A: any — loses type information\nfunction first(arr: any[]): any {\n  return arr[0];\n}\nconst x = first([1, 2, 3]);\n// x is 'any' — no autocomplete, no safety!\n\n// Option B: Overloads — repetitive\nfunction firstNumber(arr: number[]): number { return arr[0]; }\nfunction firstString(arr: string[]): string { return arr[0]; }\n\`\`\`\n\n### Solution: Generics\n\`\`\`typescript\nfunction first<T>(arr: T[]): T {\n  return arr[0];\n}\n\nconst n = first([1, 2, 3]);     // n: number ✅\nconst s = first(["a", "b"]);   // s: string ✅\n\`\`\`\n\n### Generic Constraints\n\`\`\`typescript\n// Constrain T to have a .length property\nfunction logLength<T extends { length: number }>(item: T): T {\n  console.log(item.length);\n  return item;\n}\nlogLength("hello");    // OK: string has .length\nlogLength([1, 2, 3]);  // OK: array has .length\nlogLength(42);         // Error: number has no .length\n\`\`\`\n\n### Generic Interfaces\n\`\`\`typescript\ninterface ApiResponse<T> {\n  data: T;\n  error: string | null;\n  status: number;\n}\n\ntype UserResponse = ApiResponse<User>;        // data: User\ntype ListResponse = ApiResponse<User[]>;      // data: User[]\n\`\`\`\n\n### Real-World Example: useState type\n\`\`\`typescript\n// React's useState is generic\nconst [count, setCount] = useState<number>(0);\nconst [user, setUser] = useState<User | null>(null);\n\`\`\``,
    eli5: "TypeScript generics are like a magic box that can hold any type of thing, but once you put something in, TypeScript remembers what it is. So if you put numbers in, you know you'll get numbers out.",
    tags: JSON.stringify(["frontend", "typescript", "generics", "type-safety"]),
  },

  // ── NODE.JS ───────────────────────────────────────────────────────────────
  {
    id: id(), channel: "backend", subChannel: "nodejs", difficulty: "intermediate",
    question: "What is Node.js's event loop and how does it handle non-blocking I/O? What is libuv?",
    answer: "Node.js uses a single-threaded event loop powered by libuv (a C library). I/O operations (file read, network) are delegated to the OS or thread pool (libuv), and callbacks are queued when complete. The event loop phases: timers → pending I/O → idle → poll → check (setImmediate) → close callbacks. libuv provides the thread pool for CPU-bound I/O operations (DNS, file system).",
    explanation: `## Node.js Event Loop Architecture\n\n### Core Insight\nNode.js is single-threaded for JS execution but delegates blocking I/O to the OS (via epoll/kqueue/IOCP) or libuv's thread pool. This is why I/O is non-blocking without multi-threading.\n\n### Event Loop Phases\n\`\`\`\n   ┌───────────────────────────┐\n   │           timers          │ ← setTimeout, setInterval callbacks\n   └──────────────┬────────────┘\n   ┌──────────────┴────────────┐\n   │     pending callbacks     │ ← I/O errors from prev iteration\n   └──────────────┬────────────┘\n   ┌──────────────┴────────────┐\n   │         poll              │ ← Retrieve new I/O events\n   └──────────────┬────────────┘\n   ┌──────────────┴────────────┐\n   │         check             │ ← setImmediate callbacks\n   └──────────────┬────────────┘\n   ┌──────────────┴────────────┐\n   │      close callbacks      │ ← socket.on('close', ...)\n   └──────────────┬────────────┘\n         (back to timers)\n\`\`\`\n\n### libuv Thread Pool\n- Default 4 threads (UV_THREADPOOL_SIZE=4)\n- Handles: DNS lookups, file system operations, crypto operations\n- Network I/O uses OS async APIs (no thread pool needed)\n\n### Why Node is Fast for I/O\n\`\`\`javascript\n// This DON'T block the event loop:\nfs.readFile('file.txt', callback);  // Delegated to OS\nhttp.get(url, callback);            // Async network\n\n// These DO block (avoid in production):\nfs.readFileSync('file.txt');        // Blocks thread!\ncrypto.pbkdf2Sync(pw, salt, n, 64, 'sha512')  // Heavy CPU!\n\`\`\`\n\n### Avoid Blocking the Event Loop\n- Use async versions of all I/O functions\n- Move CPU-heavy work to worker_threads or child_process\n- Use cluster module to utilize multiple CPU cores`,
    eli5: "Node.js is like a single chef in a kitchen. When an order comes in, instead of waiting for the oven, the chef gives the oven job to a helper and immediately takes the next order. When the oven is done, the helper taps the chef on the shoulder to deliver the food.",
    tags: JSON.stringify(["backend", "nodejs", "event-loop", "libuv", "non-blocking"]),
  },
  {
    id: id(), channel: "backend", subChannel: "microservices", difficulty: "advanced",
    question: "What is the SAGA pattern in microservices and when do you need it?",
    answer: "The SAGA pattern manages distributed transactions across multiple microservices without a single 2-phase commit (which creates tight coupling). A saga is a sequence of local transactions. If one fails, compensating transactions roll back previous steps. Two implementations: Choreography (event-driven) and Orchestration (central coordinator). Needed when: multiple services must succeed/fail together (e.g., order placement, payment, inventory).",
    explanation: `## SAGA Pattern\n\n### The Problem\nIn microservices, you can't use a traditional database transaction across services.\nExample: Creating an order requires:\n1. Order Service: create order\n2. Payment Service: charge customer  \n3. Inventory Service: reduce stock\n4. Notification Service: send email\n\nIf step 3 fails, you need to refund the payment (step 2) and cancel the order (step 1).\n\n### Choreography SAGA (Event-Driven)\n\`\`\`\nOrder Service\n  → publishes OrderCreated event\nPayment Service\n  → subscribes, charges, publishes PaymentCompleted\nInventory Service\n  → subscribes, reduces stock, publishes InventoryReserved\n--- If inventory fails ---\nInventory Service\n  → publishes InventoryFailed\nPayment Service\n  → subscribes InventoryFailed, publishes PaymentRefunded (compensating)\nOrder Service\n  → subscribes, cancels order\n\`\`\`\n\nPros: Loose coupling, no single point of failure  \nCons: Hard to trace, complex event chains\n\n### Orchestration SAGA (Central Coordinator)\n\`\`\`\nSAGA Orchestrator (state machine)\n  → tells Order Service: create order\n  → tells Payment Service: charge\n  → tells Inventory Service: reserve\n  → if any fails: tells each service to compensate\n\`\`\`\n\nPros: Easier to trace, explicit flow  \nCons: Orchestrator is a single point of failure, centralized logic\n\n### Idempotency Requirement\nAll operations in a saga must be idempotent — they can be safely retried without side effects.`,
    eli5: "SAGA is a way to do 'undo' across multiple different services. Like a series of dominoes — if one falls wrong, you have a plan to push all the previous ones back upright.",
    tags: JSON.stringify(["backend", "microservices", "saga", "distributed-transactions"]),
  },

  // ── KUBERNETES ADVANCED ───────────────────────────────────────────────────
  {
    id: id(), channel: "kubernetes", subChannel: "networking", difficulty: "advanced",
    question: "What is a Kubernetes Service and what are the differences between ClusterIP, NodePort, and LoadBalancer types?",
    answer: "A Service provides stable network access to pods (which have ephemeral IPs). ClusterIP: internal cluster access only (default). NodePort: exposes service on each Node's IP at a static port (30000-32767) — external access via NodeIP:NodePort. LoadBalancer: provisions a cloud load balancer (external IP) — used in production on cloud providers.",
    explanation: `## Kubernetes Services\n\n### Why Services Exist\nPods get new IPs when they restart or scale. Services provide a stable IP/DNS name that load-balances to pod replicas.\n\n### ClusterIP (default)\n\`\`\`yaml\napiVersion: v1\nkind: Service\nmetadata:\n  name: my-service\nspec:\n  type: ClusterIP  # Default\n  selector:\n    app: myapp\n  ports:\n  - port: 80\n    targetPort: 8080\n\`\`\`\n- **Access**: Only within the cluster\n- **Use case**: Internal microservice communication\n- **DNS**: \`my-service.namespace.svc.cluster.local\`\n\n### NodePort\n\`\`\`yaml\nspec:\n  type: NodePort\n  ports:\n  - port: 80\n    targetPort: 8080\n    nodePort: 31000  # Optional: auto-assigned if not set\n\`\`\`\n- **Access**: \`<AnyNodeIP>:31000\` from outside cluster\n- **Use case**: Dev/test, on-premise clusters without cloud LB\n- **Limitation**: Port range 30000-32767, exposes node IPs\n\n### LoadBalancer\n\`\`\`yaml\nspec:\n  type: LoadBalancer\n  ports:\n  - port: 80\n    targetPort: 8080\n\`\`\`\n- **Access**: Cloud provider creates external LB with public IP\n- **Use case**: Production workloads on AWS/GKE/AKS\n- **Cost**: Each LoadBalancer = 1 cloud LB (can be expensive)\n\n### Comparison\n| Type | External Access | Use Case |\n|------|----------------|----------|\n| ClusterIP | No | Internal services |\n| NodePort | Yes (via node IP) | Dev/test |\n| LoadBalancer | Yes (via LB IP) | Production |\n| Ingress | Yes (HTTP/HTTPS routing) | Production (preferred) |`,
    eli5: "A Kubernetes Service is like a receptionist for your pods. ClusterIP is an internal receptionist (only employees can call). NodePort is a phone number from outside that rings through. LoadBalancer is a fancy front-desk number that auto-routes to the right person.",
    tags: JSON.stringify(["kubernetes", "networking", "services", "clusterip", "loadbalancer"]),
  },
  {
    id: id(), channel: "kubernetes", subChannel: "storage", difficulty: "intermediate",
    question: "What is the difference between a PersistentVolume (PV), PersistentVolumeClaim (PVC), and StorageClass in Kubernetes?",
    answer: "PersistentVolume (PV): actual storage resource (disk, NFS, cloud volume) provisioned by an admin. PersistentVolumeClaim (PVC): a request for storage by a pod (size, access mode). StorageClass: enables dynamic provisioning — when a PVC is created, it automatically provisions a PV using the specified provisioner (e.g., AWS EBS, GCP PD). PVC binds to a compatible PV.",
    explanation: `## Kubernetes Storage\n\n### Static vs Dynamic Provisioning\n\n**Static**: Admin manually creates PVs, users claim them via PVCs.\n**Dynamic**: StorageClass + PVC = automatic PV creation.\n\n### PersistentVolume (PV)\n\`\`\`yaml\napiVersion: v1\nkind: PersistentVolume\nmetadata:\n  name: my-pv\nspec:\n  capacity:\n    storage: 10Gi\n  accessModes:\n    - ReadWriteOnce  # RWO: one node at a time\n  persistentVolumeReclaimPolicy: Retain\n  hostPath:\n    path: /data/my-pv\n\`\`\`\n\n### PersistentVolumeClaim (PVC)\n\`\`\`yaml\napiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: my-pvc\nspec:\n  accessModes:\n    - ReadWriteOnce\n  resources:\n    requests:\n      storage: 5Gi\n  storageClassName: fast-ssd  # References StorageClass\n\`\`\`\n\n### StorageClass (Dynamic Provisioning)\n\`\`\`yaml\napiVersion: storage.k8s.io/v1\nkind: StorageClass\nmetadata:\n  name: fast-ssd\nprovisioner: kubernetes.io/aws-ebs\nparameters:\n  type: gp3\n  iopsPerGB: "10"\n\`\`\`\n\n### Access Modes\n| Mode | Abbreviation | Description |\n|------|-------------|-------------|\n| ReadWriteOnce | RWO | One node, read/write |\n| ReadOnlyMany | ROX | Many nodes, read-only |\n| ReadWriteMany | RWX | Many nodes, read/write |`,
    eli5: "PersistentVolume is a USB drive that the admin sets up. PersistentVolumeClaim is a post-it saying 'I need a 5GB USB drive'. StorageClass is a magic machine that automatically creates the USB drive as soon as you put in the post-it.",
    tags: JSON.stringify(["kubernetes", "storage", "pv", "pvc", "storageclass"]),
  },

  // ── NETWORKING ────────────────────────────────────────────────────────────
  {
    id: id(), channel: "networking", subChannel: "protocols", difficulty: "intermediate",
    question: "What happens when you type 'https://google.com' in a browser and press Enter? Walk through the full request lifecycle.",
    answer: "1. DNS resolution: browser cache → OS cache → DNS resolver → root/TLD/authoritative DNS → returns IP. 2. TCP 3-way handshake to port 443. 3. TLS handshake (certificate verification, key exchange). 4. HTTP GET request sent. 5. Server processes, returns HTTP response. 6. Browser parses HTML, fetches assets (CSS/JS/images), renders page.",
    explanation: `## Full Browser Request Lifecycle\n\n### Step 1: DNS Resolution\n\`\`\`\n1. Browser cache: checked first (chrome://net-internals/#dns)\n2. OS cache: /etc/hosts, local DNS cache\n3. Recursive DNS resolver (your ISP or 8.8.8.8)\n4. Root name server → .com TLD server → google.com authoritative\n5. Returns: 142.250.80.46\n\`\`\`\n\n### Step 2: TCP Handshake (Port 443)\n\`\`\`\nClient → SYN → Server\nClient ← SYN-ACK ← Server\nClient → ACK → Server\n(Connection established)\n\`\`\`\n\n### Step 3: TLS Handshake\n\`\`\`\n1. Client Hello: TLS version, cipher suites, random\n2. Server Hello: chosen cipher, certificate\n3. Client verifies cert against CA\n4. Key exchange (ECDHE): derive session keys\n5. Both send Finished message (encrypted)\n\`\`\`\n\n### Step 4: HTTP Request\n\`\`\`http\nGET / HTTP/2\nHost: google.com\nAccept: text/html\nAccept-Encoding: gzip\nCookie: ...\n\`\`\`\n\n### Step 5: Server Response\n\`\`\`http\nHTTP/2 200 OK\nContent-Type: text/html; charset=UTF-8\nContent-Encoding: gzip\n\n<!doctype html><html>...\n\`\`\`\n\n### Step 6: Browser Rendering\n1. Parse HTML → DOM tree\n2. Parse CSS → CSSOM tree\n3. DOM + CSSOM → Render tree\n4. Layout (calculate positions)\n5. Paint (pixels on screen)\n6. Composite (GPU layers)`,
    eli5: "Typing a URL is like mailing a letter. First you look up the address in the phone book (DNS). Then you knock on the door and agree on a secret code (TLS). Then you send your letter (HTTP request). The server reads it, writes back (HTTP response), and your browser draws what it receives.",
    tags: JSON.stringify(["networking", "protocols", "dns", "http", "tls"]),
  },
  {
    id: id(), channel: "networking", subChannel: "protocols", difficulty: "intermediate",
    question: "What is the difference between TCP and UDP? When would you use UDP over TCP?",
    answer: "TCP: connection-oriented (3-way handshake), reliable (guaranteed delivery with retransmission), ordered, flow-controlled, congestion-controlled. UDP: connectionless, no delivery guarantee, no ordering, no congestion control — but much lower overhead. Use UDP for: real-time video/audio streaming, online gaming (latency > reliability), DNS queries, VoIP.",
    explanation: `## TCP vs UDP\n\n| Feature | TCP | UDP |\n|---------|-----|-----|\n| Connection | 3-way handshake | Connectionless |\n| Reliability | Guaranteed delivery | Best-effort |\n| Ordering | Yes (sequence numbers) | No |\n| Flow control | Yes (receiver window) | No |\n| Congestion control | Yes (slow start, AIMD) | No |\n| Header size | 20+ bytes | 8 bytes |\n| Latency | Higher | Lower |\n| Use case | HTTP, email, file transfer | Video, gaming, DNS |\n\n### Why UDP for Real-Time?\nIn a video call, if a packet arrives late, it's useless — you've already played that frame. Better to skip it than wait for retransmission. UDP lets the application decide: "drop the packet or use the last good frame."\n\n### TCP Use Cases\n- HTTP/HTTPS, FTP, SMTP: File integrity matters\n- Banking: Never drop a transaction\n- SSH: Can't miss any character\n\n### UDP Use Cases\n- **Video streaming** (YouTube, Netflix): QUIC (HTTP/3) over UDP\n- **Online gaming**: Low latency > reliability\n- **DNS**: Small query/response, retransmit at app layer if needed\n- **VoIP**: Drop packet < introduce lag\n- **IoT sensors**: Occasional loss acceptable\n\n### QUIC (HTTP/3)\nQUIC is built on UDP but adds reliability at the application layer:\n- Faster connection setup (0-RTT)\n- Per-stream reliability (1 lost packet doesn't block others)\n- Built-in encryption (TLS 1.3 by default)\n- Used by Chrome, YouTube, Google services`,
    eli5: "TCP is like certified mail — guaranteed to arrive in order, but slower. UDP is like shouting across a room — fast but some words might not reach. Use UDP when being a bit late or missing something is better than being slow.",
    tags: JSON.stringify(["networking", "tcp", "udp", "protocols", "reliability"]),
  },

  // ── COMPLEXITY ANALYSIS ───────────────────────────────────────────────────
  {
    id: id(), channel: "complexity-analysis", subChannel: "big-o", difficulty: "beginner",
    question: "Explain Big O notation. What is the difference between O(1), O(log n), O(n), O(n log n), and O(n²)?",
    answer: "Big O describes the upper bound of an algorithm's time/space growth as input size n grows. O(1): constant — doesn't grow (hash table lookup). O(log n): logarithmic — halves each step (binary search). O(n): linear — grows proportionally (linear scan). O(n log n): linearithmic — most efficient comparison sorts (merge sort). O(n²): quadratic — nested loops over input (bubble sort).",
    explanation: `## Big O Notation\n\nDescribes **growth rate** of time or space as a function of input size n.\n\n### Common Complexities (best to worst)\n\n| Notation | Name | Example | n=1000 ops |\n|----------|------|---------|------------|\n| O(1) | Constant | Hash table lookup | 1 |\n| O(log n) | Logarithmic | Binary search | ~10 |\n| O(n) | Linear | Linear scan | 1,000 |\n| O(n log n) | Linearithmic | Merge sort | ~10,000 |\n| O(n²) | Quadratic | Bubble sort | 1,000,000 |\n| O(2ⁿ) | Exponential | Recursive Fibonacci | > universe |\n\n### Rules\n1. **Drop constants**: O(2n) → O(n)\n2. **Drop lower terms**: O(n² + n) → O(n²)\n3. **Worst case**: O(n) for linear search even though it might find element at position 1\n\n### Examples\n\`\`\`python\n# O(1) - constant\ndef get_first(arr): return arr[0]\n\n# O(log n) - binary search\ndef binary_search(arr, t): ...  # Halves search space\n\n# O(n) - single loop\ndef sum_array(arr): return sum(arr)\n\n# O(n²) - nested loops\ndef bubble_sort(arr):\n    for i in range(n):\n        for j in range(n - i - 1):  # Nested!\n            ...\n\`\`\`\n\n### Space Complexity\nSame notation but for memory:\n- O(1): iterative solution\n- O(n): storing n items in array\n- O(log n): recursive binary search (call stack depth)`,
    eli5: "Big O is like describing how long cooking takes as you add guests. O(1) = always 1 minute. O(n) = 1 minute per guest. O(n²) = talk to each guest for each other guest — gets really slow with many guests.",
    tags: JSON.stringify(["complexity-analysis", "big-o", "time-complexity", "space-complexity"]),
  },
];

async function main() {
  console.log(`Seeding ${questions.length} questions (data structures, TypeScript, Node.js, networking, complexity)...`);
  let count = 0;
  for (const q of questions) {
    await client.execute({
      sql: `INSERT OR IGNORE INTO questions
        (id, question, answer, explanation, eli5, difficulty, tags, channel, sub_channel, status, is_new, created_at, last_updated)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,
      args: [q.id, q.question, q.answer, q.explanation, q.eli5 ?? null, q.difficulty, q.tags, q.channel, q.subChannel, "active", 1, NOW, NOW],
    });
    count++;
    console.log(`[${q.channel}] ${q.question.slice(0, 60)}...`);
  }
  console.log(`\nDone! ${count} questions inserted.`);
  client.close();
}
main().catch((e) => { console.error(e); process.exit(1); });
