/**
 * Issue #60 — Batch 1: Questions for algorithms, system-design, frontend
 * Run: npx tsx scripts/seed-questions-batch1.ts
 */
import { createClient } from "@libsql/client";
import crypto from "crypto";

const client = createClient({ url: "file:local.db" });
const NOW = new Date().toISOString();
const id = () => crypto.randomUUID();

const questions = [
  // ── ALGORITHMS ────────────────────────────────────────────────────────────
  {
    id: id(), channel: "algorithms", subChannel: "sorting", difficulty: "intermediate",
    question: "What is the average and worst-case time complexity of quicksort, and when does quicksort degrade to O(n²)?",
    answer: "Average case: O(n log n). Worst case: O(n²) when the pivot is always the smallest or largest element — i.e., when sorting an already-sorted or reverse-sorted array with a naive pivot strategy.",
    explanation: `## Quicksort Complexity\n\n| Case | Time | Space |\n|------|------|-------|\n| Best | O(n log n) | O(log n) |\n| Average | O(n log n) | O(log n) |\n| Worst | O(n²) | O(n) |\n\n## Why Worst Case is O(n²)\nQuicksort partitions around a pivot. If the pivot is always the min or max element:\n- Partition produces one subarray of size n-1 and one of size 0\n- Recurrence: T(n) = T(n-1) + O(n) → O(n²)\n\n## How to Avoid\n- **Median-of-three**: Choose pivot as median of first, middle, last elements\n- **Random pivot**: Randomly select pivot — expected O(n log n) for any input\n- **Introsort**: Switches to heapsort when recursion depth exceeds 2*log(n)\n\n## Why Still Preferred\nDespite O(n²) worst case, quicksort is preferred in practice due to:\n- Excellent cache locality (in-place)\n- Small constants in O(n log n)\n- Tail-recursion optimization possible\n\n\`\`\`python\ndef quicksort(arr, lo, hi):\n    if lo < hi:\n        pivot_idx = partition(arr, lo, hi)  # O(n)\n        quicksort(arr, lo, pivot_idx - 1)   # left half\n        quicksort(arr, pivot_idx + 1, hi)   # right half\n\`\`\``,
    eli5: "Quicksort picks a middle number, puts smaller numbers on the left and bigger on the right, then repeats. It's usually fast, but if it always picks the smallest number as the middle, it has to do way more work.",
    tags: JSON.stringify(["algorithms", "sorting", "quicksort", "complexity"]),
  },
  {
    id: id(), channel: "algorithms", subChannel: "sorting", difficulty: "intermediate",
    question: "How does merge sort differ from quicksort in terms of stability, space complexity, and use cases?",
    answer: "Merge sort is stable (preserves relative order of equal elements), uses O(n) extra space, and guarantees O(n log n) in all cases. Quicksort is unstable, uses O(log n) space, averages O(n log n) but degrades to O(n²). Use merge sort when stability matters (e.g., sorting records by multiple keys) or for linked lists.",
    explanation: `## Merge Sort vs Quicksort\n\n| Property | Merge Sort | Quicksort |\n|----------|------------|----------|\n| Time (best) | O(n log n) | O(n log n) |\n| Time (avg) | O(n log n) | O(n log n) |\n| Time (worst) | O(n log n) | O(n²) |\n| Space | O(n) | O(log n) |\n| Stable | ✅ Yes | ❌ No |\n| In-place | ❌ No | ✅ Yes |\n\n## Stability\nA sort is **stable** if equal elements maintain their original relative order. Example: sorting employees by salary — if two employees have the same salary, a stable sort preserves their original name order.\n\n## When to Choose Merge Sort\n- Sorting **linked lists** (no random access needed, merge is efficient)\n- When **stability** is required\n- External sorting (data doesn't fit in memory)\n- Parallel sorting (easy to merge independently sorted chunks)\n\n## When to Choose Quicksort\n- Sorting **arrays** with random access\n- Memory-constrained environments\n- When average-case performance matters more than worst-case guarantees\n\n\`\`\`python\ndef merge_sort(arr):\n    if len(arr) <= 1: return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)  # O(n)\n\`\`\``,
    eli5: "Merge sort splits a pile of cards in half, sorts each half, then carefully combines them in order. It always takes the same amount of steps and never shuffles equal cards around, which makes it safe for sorting things that already have some order.",
    tags: JSON.stringify(["algorithms", "sorting", "merge-sort", "stability"]),
  },
  {
    id: id(), channel: "algorithms", subChannel: "graph-algorithms", difficulty: "intermediate",
    question: "What is the difference between BFS and DFS, and which should you use for finding the shortest path in an unweighted graph?",
    answer: "BFS (Breadth-First Search) explores level by level using a queue. DFS (Depth-First Search) explores as deep as possible using a stack (or recursion). For shortest path in an unweighted graph, always use BFS — it guarantees the first time you reach a node is via the shortest path.",
    explanation: `## BFS vs DFS\n\n| Property | BFS | DFS |\n|----------|-----|-----|\n| Data structure | Queue | Stack (or recursion) |\n| Order | Level by level | Branch by branch |\n| Space | O(w) — width of tree | O(h) — height of tree |\n| Shortest path | ✅ Yes (unweighted) | ❌ No |\n| Cycle detection | Yes | Yes |\n| Topological sort | No | ✅ Yes |\n\n## Why BFS Finds Shortest Path\nBFS visits all nodes at distance 1 before distance 2, all at distance 2 before 3, etc. The first time you reach the destination, it must be via the shortest path.\n\n\`\`\`python\nfrom collections import deque\n\ndef bfs_shortest_path(graph, start, end):\n    queue = deque([(start, [start])])\n    visited = {start}\n    while queue:\n        node, path = queue.popleft()\n        if node == end:\n            return path\n        for neighbor in graph[node]:\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append((neighbor, path + [neighbor]))\n    return None\n\`\`\`\n\n## When to Use DFS\n- Topological sorting\n- Detecting cycles\n- Finding connected components\n- Solving mazes (any path, not shortest)\n- Tree traversals (inorder/preorder/postorder)`,
    eli5: "BFS is like a wave spreading outward in a pond — it reaches nearby places first, so the first time it finds a destination it took the shortest route. DFS is like exploring a maze by always going as far as possible before turning back.",
    tags: JSON.stringify(["algorithms", "graph-algorithms", "bfs", "dfs", "shortest-path"]),
  },
  {
    id: id(), channel: "algorithms", subChannel: "dynamic-programming", difficulty: "advanced",
    question: "Explain the 0/1 Knapsack problem and how dynamic programming solves it. What is the time and space complexity?",
    answer: "Given items with weights and values and a knapsack capacity W, find the maximum value you can carry without exceeding W. Each item can be taken (1) or not (0). DP solution: build a 2D table dp[i][w] = max value using first i items with capacity w. Time: O(n×W), Space: O(n×W), optimized to O(W) with 1D DP.",
    explanation: `## 0/1 Knapsack Problem\n\n**Problem**: n items, each with weight w[i] and value v[i]. Knapsack capacity W. Maximize total value without exceeding W.\n\n## DP Recurrence\n\`\`\`\ndp[i][w] = max(\n    dp[i-1][w],              # Don't take item i\n    dp[i-1][w - w[i]] + v[i] # Take item i (if w[i] <= w)\n)\n\`\`\`\n\n## Implementation\n\`\`\`python\ndef knapsack(weights, values, W):\n    n = len(weights)\n    dp = [[0] * (W + 1) for _ in range(n + 1)]\n    \n    for i in range(1, n + 1):\n        for w in range(W + 1):\n            # Don't take item i-1\n            dp[i][w] = dp[i-1][w]\n            # Take item i-1 if it fits\n            if weights[i-1] <= w:\n                dp[i][w] = max(dp[i][w],\n                    dp[i-1][w - weights[i-1]] + values[i-1])\n    \n    return dp[n][W]  # Maximum value\n\`\`\`\n\n## Space-Optimized (O(W))\n\`\`\`python\ndef knapsack_optimized(weights, values, W):\n    dp = [0] * (W + 1)\n    for i in range(len(weights)):\n        # Iterate backwards to avoid using item twice\n        for w in range(W, weights[i] - 1, -1):\n            dp[w] = max(dp[w], dp[w - weights[i]] + values[i])\n    return dp[W]\n\`\`\`\n\n## Complexity\n| | Time | Space |\n|--|------|-------|\n| 2D DP | O(n×W) | O(n×W) |\n| 1D DP | O(n×W) | O(W) |\n\n**Note**: Not polynomial — W can be exponentially large (pseudo-polynomial).`,
    eli5: "Imagine you have a backpack and a bunch of items. You can't take everything. The knapsack problem figures out the best combination of items to pack to get the most value without overloading your backpack.",
    tags: JSON.stringify(["algorithms", "dynamic-programming", "knapsack", "optimization"]),
  },
  {
    id: id(), channel: "algorithms", subChannel: "searching", difficulty: "beginner",
    question: "How does binary search work, what are its preconditions, and what is its time complexity?",
    answer: "Binary search finds a target in a sorted array by repeatedly halving the search space. It compares the target to the middle element, then searches only the left or right half. Precondition: array must be sorted. Time: O(log n). Space: O(1) iteratively, O(log n) recursively.",
    explanation: `## Binary Search Algorithm\n\n**Precondition**: Array must be sorted in ascending (or descending) order.\n\n## How It Works\n1. Start with lo=0, hi=n-1\n2. Compute mid = (lo + hi) // 2\n3. If arr[mid] == target → found!\n4. If arr[mid] < target → search right half: lo = mid + 1\n5. If arr[mid] > target → search left half: hi = mid - 1\n6. If lo > hi → not found\n\n## Implementation\n\`\`\`python\ndef binary_search(arr, target):\n    lo, hi = 0, len(arr) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2  # Avoids integer overflow\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1  # Not found\n\`\`\`\n\n## Complexity\n| | Time | Space |\n|--|------|-------|\n| Iterative | O(log n) | O(1) |\n| Recursive | O(log n) | O(log n) call stack |\n\n## Why O(log n)?\nEach iteration halves the search space. Starting with n elements:\n- After 1 iteration: n/2\n- After 2 iterations: n/4\n- After k iterations: n/2^k = 1 → k = log₂(n)\n\n## Common Pitfalls\n- **Integer overflow**: Use \`mid = lo + (hi - lo) // 2\` not \`(lo + hi) // 2\` in languages without BigInt\n- **Off-by-one errors**: Make sure loop condition is \`lo <= hi\`, not \`lo < hi\`\n- **Forgetting sorted precondition**: Binary search on unsorted data gives wrong results`,
    eli5: "Binary search is like finding a word in a dictionary: open to the middle, check if your word comes before or after, then throw away the half that can't contain your word. Repeat until found!",
    tags: JSON.stringify(["algorithms", "searching", "binary-search", "complexity"]),
  },
  {
    id: id(), channel: "algorithms", subChannel: "graph-algorithms", difficulty: "advanced",
    question: "What is Dijkstra's algorithm and what type of graph does it work on? How does it differ from Bellman-Ford?",
    answer: "Dijkstra's finds shortest paths from a source to all nodes in a weighted graph with non-negative edge weights. It uses a priority queue for O((V+E) log V). Bellman-Ford handles negative edges and detects negative cycles but is O(VE) — much slower.",
    explanation: `## Dijkstra's Algorithm\n\n**Use case**: Single-source shortest path in graphs with **non-negative** edge weights.\n\n\`\`\`python\nimport heapq\n\ndef dijkstra(graph, start):\n    dist = {node: float('inf') for node in graph}\n    dist[start] = 0\n    pq = [(0, start)]  # (distance, node)\n    \n    while pq:\n        d, u = heapq.heappop(pq)\n        if d > dist[u]: continue  # Outdated entry\n        for v, weight in graph[u]:\n            if dist[u] + weight < dist[v]:\n                dist[v] = dist[u] + weight\n                heapq.heappush(pq, (dist[v], v))\n    return dist\n\`\`\`\n\n## Why Non-Negative Weights Only?\nDijkstra uses a greedy approach: once a node is popped from the priority queue, its distance is final. With negative edges, a later path could undercut an already-finalized distance.\n\n## Dijkstra vs Bellman-Ford\n| | Dijkstra | Bellman-Ford |\n|--|----------|-------------|\n| Negative edges | ❌ No | ✅ Yes |\n| Negative cycles | Cannot detect | ✅ Detects |\n| Time complexity | O((V+E) log V) | O(VE) |\n| Use case | Road maps, GPS | Arbitrage detection, routing protocols |\n\n## Complexity\n- With binary heap: O((V+E) log V)\n- With Fibonacci heap: O(E + V log V) — theoretical optimum`,
    eli5: "Dijkstra's algorithm is like GPS navigation — it always explores the shortest current route first, building the map of shortest paths outward from your starting point.",
    tags: JSON.stringify(["algorithms", "graph-algorithms", "dijkstra", "shortest-path"]),
  },

  // ── SYSTEM DESIGN ─────────────────────────────────────────────────────────
  {
    id: id(), channel: "system-design", subChannel: "caching", difficulty: "intermediate",
    question: "What are the main cache eviction policies (LRU, LFU, FIFO) and when should you use each?",
    answer: "LRU (Least Recently Used) evicts the oldest-accessed item — best for temporal locality. LFU (Least Frequently Used) evicts the least-accessed item — best when popularity distribution is stable. FIFO (First In, First Out) evicts the oldest inserted item — simple but ignores access patterns. LRU is the most common default choice.",
    explanation: `## Cache Eviction Policies\n\n### LRU — Least Recently Used\n- Evicts the item that has not been accessed for the longest time\n- Assumes: recently accessed items will be accessed again soon\n- Implementation: doubly-linked list + hash map → O(1) get/put\n- **Best for**: Web caches, CDN, database buffer pools\n\n### LFU — Least Frequently Used\n- Evicts the item accessed the fewest total times\n- Assumes: popular items will remain popular\n- Implementation: min-heap or frequency buckets\n- **Best for**: Recommendation systems, static content caches\n- **Downside**: New items with frequency=1 are quickly evicted (cache pollution)\n\n### FIFO — First In, First Out\n- Evicts the oldest inserted item regardless of access\n- Simple queue-based implementation\n- **Best for**: Simple scenarios where recency/frequency don't matter\n- **Downside**: Ignores temporal and frequency patterns\n\n### TLRU — Time-aware LRU\n- Adds TTL (time-to-live) to LRU\n- Items expire after TTL regardless of access\n- **Best for**: Session stores, API rate limiters\n\n## Comparison\n| Policy | Time Complexity | Space | Use Case |\n|--------|----------------|-------|----------|\n| LRU | O(1) | O(n) | General purpose |\n| LFU | O(log n) or O(1) | O(n) | Content popularity |\n| FIFO | O(1) | O(n) | Simple workloads |\n\n**Real World**: Redis uses LRU or LFU (configurable). CPU caches typically use LRU variants.`,
    eli5: "Cache eviction is like deciding which book to remove from a small bookshelf. LRU removes the one you haven't touched in the longest time. LFU removes the one you've read the fewest times. FIFO removes the oldest one you put there.",
    tags: JSON.stringify(["system-design", "caching", "lru", "lfu", "eviction"]),
  },
  {
    id: id(), channel: "system-design", subChannel: "distributed-systems", difficulty: "advanced",
    question: "Explain the CAP theorem. Can a distributed system ever satisfy all three properties simultaneously?",
    answer: "CAP theorem states a distributed system can guarantee at most two of three: Consistency (all nodes see the same data at the same time), Availability (every request gets a response), and Partition Tolerance (system works despite network partitions). Since network partitions are unavoidable in real distributed systems, you always choose between CP (consistent but may reject requests) or AP (always responds but may return stale data).",
    explanation: `## CAP Theorem\n\nProven by Eric Brewer (2000), formalized by Gilbert & Lynch (2002).\n\n### The Three Properties\n- **Consistency (C)**: Every read receives the most recent write or an error. All nodes have the same view of data at the same time.\n- **Availability (A)**: Every request (to a non-failed node) receives a non-error response — but it might be stale.\n- **Partition Tolerance (P)**: System continues operating despite network partitions (nodes can't communicate).\n\n### Why P is Non-Negotiable\nNetwork partitions happen in any distributed system (hardware failure, network congestion, data center splits). You CANNOT build a reliable distributed system without partition tolerance. Therefore, the real choice is **CP vs AP**.\n\n### Examples\n| System | Choice | Behavior |\n|--------|--------|----------|\n| HBase, Zookeeper | CP | Returns error during partition |\n| Cassandra, CouchDB | AP | Returns potentially stale data |\n| Traditional RDBMS | CA | Single node, no partition tolerance |\n\n### Beyond CAP: PACELC\nCAP only addresses partition scenarios. **PACELC** extends it:\n- If Partition: choose Availability or Consistency\n- Else (no partition): choose Latency or Consistency\n\n### Real-World Impact\n- **Banking**: Choose CP (never show wrong balance)\n- **Social media likes**: Choose AP (stale count is acceptable)\n- **Shopping cart**: Usually AP (availability matters more than exact count)`,
    eli5: "In a distributed system, you can't have everything: fast updates everywhere, always-on service, AND reliability when the network breaks. The CAP theorem says pick any two. In practice, you always need 'it works when the network breaks', so you choose between 'always fast' or 'always accurate'.",
    tags: JSON.stringify(["system-design", "distributed-systems", "cap-theorem", "consistency"]),
  },
  {
    id: id(), channel: "system-design", subChannel: "databases", difficulty: "intermediate",
    question: "When would you choose a NoSQL database over a relational database? Give concrete examples.",
    answer: "Choose NoSQL for: (1) Massive scale-out needs (horizontal sharding), (2) Flexible/evolving schemas, (3) Specific data models (documents, graphs, time-series), (4) Ultra-low latency requirements. Examples: MongoDB for product catalogs with variable attributes, Cassandra for time-series sensor data, Redis for session caching, Neo4j for social graphs.",
    explanation: `## NoSQL vs RDBMS Decision\n\n### Choose NoSQL When\n1. **Horizontal scalability**: Need to shard across many nodes — Cassandra, DynamoDB\n2. **Schema flexibility**: Product catalog where each product has different attributes\n3. **Document model**: JSON-centric data (MongoDB, CouchDB)\n4. **High write throughput**: IoT sensor data, event logs (Cassandra, InfluxDB)\n5. **Graph relationships**: Social networks, fraud detection (Neo4j)\n6. **Caching**: Session stores, leaderboards (Redis)\n\n### Choose RDBMS When\n1. **Complex queries**: Multi-table JOINs, ad-hoc analytics\n2. **ACID transactions**: Banking, inventory, order management\n3. **Data integrity**: Foreign keys, constraints, normalized data\n4. **Reporting**: Business intelligence, regulatory compliance\n5. **Relationships are complex**: Many-to-many with rich join conditions\n\n### Common NoSQL Databases by Type\n| Type | Database | Use Case |\n|------|----------|----------|\n| Document | MongoDB, Firestore | Product catalog, CMS |\n| Key-Value | Redis, DynamoDB | Caching, sessions |\n| Wide-column | Cassandra, HBase | Time-series, analytics |\n| Graph | Neo4j, Neptune | Social networks, fraud |\n| Time-series | InfluxDB, TimescaleDB | Metrics, IoT |\n\n### The Myth\nNoSQL ≠ no schema. MongoDB enforces schemas at the application layer. "NoSQL" means "Not Only SQL" — many NoSQL databases now support SQL-like query languages.`,
    eli5: "Regular databases are like organized filing cabinets with strict folders. NoSQL databases are more like big flexible storage areas — great when you have tons of different-shaped things to store and need to grow really fast.",
    tags: JSON.stringify(["system-design", "databases", "nosql", "sql", "trade-offs"]),
  },
  {
    id: id(), channel: "system-design", subChannel: "api-design", difficulty: "intermediate",
    question: "What is rate limiting, why is it important, and what algorithms are commonly used to implement it?",
    answer: "Rate limiting controls how many requests a client can make in a time window, protecting the service from abuse, DDoS, and resource exhaustion. Common algorithms: Token Bucket (allows burst, smooth long-term rate), Sliding Window Log (accurate, memory-heavy), Fixed Window Counter (simple, boundary burst issue), and Leaky Bucket (strict output rate).",
    explanation: `## Rate Limiting\n\n### Why It's Important\n- **DDoS protection**: Prevents a single client from overwhelming the service\n- **Fair usage**: Ensures all users get equitable access\n- **Cost control**: Prevents runaway API usage and compute costs\n- **SLA protection**: Maintains response time guarantees for other users\n\n### Algorithms\n\n#### 1. Token Bucket\n- Bucket holds up to **burst_size** tokens\n- Tokens refill at a fixed rate (e.g., 10/second)\n- Each request consumes 1 token; if empty → reject\n- **Pros**: Allows bursting, easy to implement\n- **Used by**: AWS API Gateway, Stripe\n\n#### 2. Sliding Window Log\n- Log every request timestamp in a sorted set\n- Count requests in [now - window, now]; reject if > limit\n- **Pros**: Accurate, no boundary burst\n- **Cons**: Memory-intensive (stores every timestamp)\n\n#### 3. Fixed Window Counter\n- Increment counter per window (e.g., per minute)\n- Reset at window boundary\n- **Pros**: Simple, O(1) space per client\n- **Cons**: Boundary burst (2x requests at window edge)\n\n#### 4. Sliding Window Counter\n- Hybrid: uses current and previous window counts\n- Current count = prev_count × (overlap%) + curr_count\n- **Pros**: Approximate but smooth, O(1) space\n\n#### 5. Leaky Bucket\n- Requests enter queue; process at fixed output rate\n- Excess requests are dropped\n- **Pros**: Strict output rate, prevents bursts\n- **Cons**: Delays bursty traffic\n\n### Implementation Storage\n- **Redis**: Atomic INCR with EXPIRE for counters\n- **Memcached**: Similar but simpler\n- **In-memory**: Single-server only`,
    eli5: "Rate limiting is like a bouncer at a club who only lets a certain number of people in per hour. Different strategies work like different types of bouncers — some let in small groups all at once, others make everyone form a strict single-file line.",
    tags: JSON.stringify(["system-design", "api-design", "rate-limiting", "token-bucket"]),
  },
  {
    id: id(), channel: "system-design", subChannel: "scalability", difficulty: "advanced",
    question: "What is consistent hashing and why is it preferred over modular hashing for distributed systems?",
    answer: "Consistent hashing maps both data and servers onto a virtual ring. When a server is added/removed, only K/n keys are remapped (where K=keys, n=servers). Modular hashing (key % n) remaps ~all keys when n changes, causing massive cache invalidation or data migration.",
    explanation: `## Consistent Hashing\n\n### Problem with Modular Hashing\nWith \`server = hash(key) % n\`:\n- Add 1 server: n becomes n+1, nearly ALL keys change servers\n- Remove 1 server: same problem\n- In a distributed cache, this means massive cache misses\n\n### The Ring\n1. Hash the full address space (0 to 2³²) onto a circle\n2. Map each server to a position on the ring (hash of server ID)\n3. Map each key to a position on the ring (hash of key)\n4. Key → first server clockwise from its position\n\n### Adding/Removing Servers\n- **Add server**: Only keys between the new server and its predecessor are remapped\n- **Remove server**: Only keys on the removed server move to the next server clockwise\n- **Impact**: Only K/n keys are affected, not all keys\n\n### Virtual Nodes\nProblem: Uneven distribution if few servers.\nSolution: Each physical server maps to multiple virtual nodes (e.g., 150 positions on the ring). This evens out load distribution.\n\n\`\`\`python\nimport hashlib\n\nclass ConsistentHash:\n    def __init__(self, replicas=150):\n        self.replicas = replicas\n        self.ring = {}  # hash → server\n        self.sorted_keys = []\n    \n    def add_server(self, server):\n        for i in range(self.replicas):\n            key = self._hash(f\"{server}:{i}\")\n            self.ring[key] = server\n            self.sorted_keys.append(key)\n        self.sorted_keys.sort()\n    \n    def get_server(self, key):\n        h = self._hash(key)\n        # Binary search for first server >= h\n        idx = bisect.bisect(self.sorted_keys, h) % len(self.sorted_keys)\n        return self.ring[self.sorted_keys[idx]]\n\`\`\`\n\n### Real-World Usage\n- **Cassandra**: Data partitioning\n- **Amazon DynamoDB**: Key distribution\n- **Memcached/Redis Cluster**: Sharding\n- **CDNs**: Request routing`,
    eli5: "Imagine a circular table where both party guests (data) and waiters (servers) stand at spots around the edge. Each guest gets served by the nearest waiter clockwise. If a new waiter joins or one leaves, only the nearby guests change waiters — not everyone.",
    tags: JSON.stringify(["system-design", "scalability", "consistent-hashing", "distributed-systems"]),
  },

  // ── FRONTEND ──────────────────────────────────────────────────────────────
  {
    id: id(), channel: "frontend", subChannel: "react", difficulty: "intermediate",
    question: "What is the React reconciliation algorithm (Fiber) and how does it determine what to re-render?",
    answer: "React's Fiber reconciler compares the previous virtual DOM tree with the new one (diffing). It uses three heuristics: (1) Different element types → full subtree replacement, (2) Same element type → update props, (3) List items use 'key' prop to match elements across renders. Only changed DOM nodes are actually updated.",
    explanation: `## React Reconciliation (Fiber)\n\n### Virtual DOM\nReact maintains a virtual DOM tree in memory. On each render, it creates a new tree and diffs it against the previous one (reconciliation).\n\n### Fiber Architecture\nFiber (React 16+) restructured reconciliation to be:\n- **Interruptible**: Can pause work and resume (enables Concurrent Mode)\n- **Prioritized**: High-priority updates (user input) can preempt low-priority ones (data fetching)\n- **Incremental**: Work is split into units processed across multiple frames\n\n### Diffing Heuristics\n\n#### 1. Different Element Types → Full Rebuild\n\`\`\`jsx\n// Before: <div><Counter /></div>\n// After:  <span><Counter /></span>\n// Result: div + Counter destroyed; span + new Counter created\n\`\`\`\n\n#### 2. Same Element Type → Update Props\n\`\`\`jsx\n// Before: <Button color="red" />\n// After:  <Button color="blue" />\n// Result: Only 'color' prop updated in DOM — no node recreation\n\`\`\`\n\n#### 3. Keys for Lists\n\`\`\`jsx\n// Without keys: React diffs by position\n// [A, B, C] → [X, A, B, C] means A,B,C all updated\n\n// With keys: React diffs by identity\n// Properly keyed: only X is inserted, A,B,C unchanged\n[items.map(item => <Item key={item.id} ... />)]\n\`\`\`\n\n### What Triggers Re-render?\n1. \`setState\` call\n2. Parent re-renders (unless React.memo)\n3. Context value changes\n4. \`useReducer\` dispatch\n\n### Optimization\n- **React.memo**: Skip re-render if props unchanged\n- **useMemo**: Memoize expensive calculations\n- **useCallback**: Stable function references`,
    eli5: "React keeps a snapshot of your webpage. When something changes, it compares the new snapshot to the old one and only updates the parts that are different — like only repainting the walls that changed color instead of the whole house.",
    tags: JSON.stringify(["frontend", "react", "reconciliation", "fiber", "virtual-dom"]),
  },
  {
    id: id(), channel: "frontend", subChannel: "javascript", difficulty: "intermediate",
    question: "What is the JavaScript event loop and how do microtasks differ from macrotasks? Give examples of each.",
    answer: "The event loop processes one macrotask at a time, then drains the entire microtask queue before processing the next macrotask. Macrotasks: setTimeout, setInterval, I/O callbacks, UI rendering. Microtasks: Promise callbacks (.then/.catch), queueMicrotask(), MutationObserver. Microtasks always run before the next macrotask.",
    explanation: `## JavaScript Event Loop\n\n### Single-Threaded + Non-Blocking\nJavaScript is single-threaded but uses the event loop to handle async operations without blocking the main thread.\n\n### Components\n- **Call Stack**: Where functions execute (LIFO)\n- **Web APIs**: Browser provides async capabilities (setTimeout, fetch, DOM events)\n- **Microtask Queue**: High-priority callbacks (Promises)\n- **Macrotask Queue** (Task Queue): Lower-priority callbacks (setTimeout, setInterval)\n\n### Execution Order\n1. Run current synchronous code\n2. **Drain entire microtask queue** (all .then callbacks)\n3. Run ONE macrotask\n4. Drain microtask queue again\n5. Repeat\n\n### Example\n\`\`\`javascript\nconsole.log('1');  // Sync\n\nsetTimeout(() => console.log('2'), 0);  // Macrotask\n\nPromise.resolve().then(() => console.log('3'));  // Microtask\n\nconsole.log('4');  // Sync\n\n// Output: 1, 4, 3, 2\n// Order: sync → microtask → macrotask\n\`\`\`\n\n### Microtasks vs Macrotasks\n| Category | Examples |\n|----------|----------|\n| Microtasks | Promise.then/catch/finally, queueMicrotask, MutationObserver |\n| Macrotasks | setTimeout, setInterval, setImmediate, I/O, UI rendering |\n\n### Why This Matters\n\`\`\`javascript\n// Infinite microtask loop starves macrotasks!\nfunction infiniteMicrotask() {\n  Promise.resolve().then(infiniteMicrotask);\n}\n// setTimeout callback never runs — UI freezes!\n\`\`\``,
    eli5: "JavaScript can only do one thing at a time, but it has a to-do list. 'Microtasks' are like urgent sticky notes — always done right away before anything else. 'Macrotasks' are like scheduled appointments — done one at a time after all the sticky notes are handled.",
    tags: JSON.stringify(["frontend", "javascript", "event-loop", "promises", "microtasks"]),
  },
  {
    id: id(), channel: "frontend", subChannel: "performance", difficulty: "intermediate",
    question: "What are the Core Web Vitals (LCP, CLS, INP) and what are the 'good' thresholds for each?",
    answer: "LCP (Largest Contentful Paint) measures loading performance — good if ≤2.5s. CLS (Cumulative Layout Shift) measures visual stability — good if ≤0.1. INP (Interaction to Next Paint, replaced FID) measures interactivity — good if ≤200ms. These are Google's key metrics for Search ranking.",
    explanation: `## Core Web Vitals (2024)\n\nGoogle's essential user experience metrics for web performance and Search ranking signals.\n\n### 1. LCP — Largest Contentful Paint\n- **Measures**: Loading performance\n- **What**: Time for the largest image or text block to become visible\n- **Threshold**: ✅ ≤2.5s | ⚠️ ≤4.0s | ❌ >4.0s\n- **Common causes of poor LCP**:\n  - Slow server response times\n  - Render-blocking JavaScript\n  - Unoptimized images\n  - No CDN\n- **Fix**: Optimize images, use \`loading="eager"\` on hero images, preload critical resources\n\n### 2. CLS — Cumulative Layout Shift\n- **Measures**: Visual stability\n- **What**: Unexpected shifts in page layout (score 0 = perfectly stable)\n- **Threshold**: ✅ ≤0.1 | ⚠️ ≤0.25 | ❌ >0.25\n- **Common causes**: Images/ads without dimensions, dynamically injected content, web fonts swapping\n- **Fix**: Always set width/height on images, reserve space for dynamic content\n\n### 3. INP — Interaction to Next Paint (replaced FID in March 2024)\n- **Measures**: Responsiveness to user interactions\n- **What**: Delay from user input to visual feedback (worst interaction during page visit)\n- **Threshold**: ✅ ≤200ms | ⚠️ ≤500ms | ❌ >500ms\n- **Common causes**: Long JavaScript tasks blocking the main thread\n- **Fix**: Break up long tasks, defer non-critical JS, use web workers\n\n### Measuring\n\`\`\`javascript\n// Web Vitals library\nimport { getLCP, getCLS, getINP } from 'web-vitals';\ngetLCP(console.log);\ngetCLS(console.log);\ngetINP(console.log);\n\`\`\``,
    eli5: "Core Web Vitals measure how good your website feels: how fast the main thing loads (LCP), whether stuff jumps around while loading (CLS), and how fast the page responds when you click (INP). Google uses these to rank websites.",
    tags: JSON.stringify(["frontend", "performance", "core-web-vitals", "lcp", "cls", "inp"]),
  },
  {
    id: id(), channel: "frontend", subChannel: "browser-internals", difficulty: "advanced",
    question: "What is the difference between 'blocking' and 'non-blocking' script loading in HTML, and when should you use async vs defer?",
    answer: "A plain <script> blocks HTML parsing until the script downloads and executes. 'async' downloads in parallel and executes as soon as downloaded (may execute before DOM is ready, no order guarantee). 'defer' downloads in parallel and executes after HTML is parsed but before DOMContentLoaded (maintains order). Use defer for scripts that need the DOM; async for independent scripts like analytics.",
    explanation: `## Script Loading Strategies\n\n### Plain Script (Blocking)\n\`\`\`html\n<script src="app.js"></script>\n\`\`\`\n- Parser stops when \`<script>\` is encountered\n- Downloads + executes before parsing continues\n- Causes render-blocking → poor performance\n- **Use case**: Never in the body (put at end of \`<body>\` if needed)\n\n### async\n\`\`\`html\n<script async src="analytics.js"></script>\n\`\`\`\n- Downloads in parallel (non-blocking)\n- Executes immediately when downloaded (may block briefly)\n- **No order guarantee**: Scripts execute in download order, not document order\n- DOM may not be ready when script runs\n- **Use case**: Independent scripts (analytics, ads, tracking)\n\n### defer\n\`\`\`html\n<script defer src="app.js"></script>\n\`\`\`\n- Downloads in parallel (non-blocking)\n- Executes after HTML is fully parsed\n- **Maintains document order**\n- Executes before \`DOMContentLoaded\` event\n- **Use case**: Any script that needs the DOM or has dependencies\n\n### Comparison Table\n| | Plain | async | defer |\n|--|-------|-------|-------|\n| Parse blocking | ✅ Blocks | ❌ No | ❌ No |\n| Download | Sequential | Parallel | Parallel |\n| Execution order | Document | Download | Document |\n| DOM available | No | Maybe | ✅ Yes |\n\n### Best Practice\n\`\`\`html\n<head>\n  <script defer src="main.js"></script>      <!-- needs DOM -->\n  <script async src="analytics.js"></script> <!-- independent -->\n</head>\n\`\`\``,
    eli5: "Normally, when your browser finds a script tag, it stops reading the page, downloads the script, runs it, then continues. 'async' lets the download happen in the background and runs it as soon as it's ready. 'defer' also downloads in the background but waits until the whole page is read before running.",
    tags: JSON.stringify(["frontend", "browser-internals", "script-loading", "async", "defer"]),
  },
];

async function main() {
  console.log(`Seeding ${questions.length} questions (algorithms, system-design, frontend)...`);
  let count = 0;
  for (const q of questions) {
    await client.execute({
      sql: `INSERT OR IGNORE INTO questions
        (id, question, answer, explanation, eli5, difficulty, tags, channel, sub_channel, status, is_new, created_at, last_updated)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,
      args: [q.id, q.question, q.answer, q.explanation, q.eli5 ?? null, q.difficulty, q.tags, q.channel, q.subChannel, "active", 1, NOW, NOW],
    });
    count++;
    console.log(`[${q.channel}] ${q.question.slice(0, 65)}...`);
  }
  console.log(`\nDone! ${count} questions inserted.`);
  client.close();
}
main().catch((e) => { console.error(e); process.exit(1); });
