/**
 * Issue #60 — Batch 2: Questions for backend, database, devops, security, ML, generative-ai, behavioral
 * Run: npx tsx scripts/seed-questions-batch2.ts
 */
import { createClient } from "@libsql/client";
import crypto from "crypto";

const client = createClient({ url: "file:local.db" });
const NOW = new Date().toISOString();
const id = () => crypto.randomUUID();

const questions = [
  // ── BACKEND ───────────────────────────────────────────────────────────────
  {
    id: id(), channel: "backend", subChannel: "api-design", difficulty: "intermediate",
    question: "What is the difference between REST and GraphQL, and when would you choose GraphQL over REST?",
    answer: "REST uses multiple endpoints (one per resource), returns fixed data shapes, and has over-fetching/under-fetching issues. GraphQL uses a single endpoint with a query language, clients specify exactly what data they need, eliminating over/under-fetching. Choose GraphQL when: (1) frontend has complex, variable data needs, (2) you have multiple client types (mobile/web) needing different shapes, (3) you want to reduce network requests with nested data.",
    explanation: `## REST vs GraphQL\n\n### REST Architecture\n- Multiple endpoints: \`GET /users\`, \`GET /posts\`, \`GET /comments\`\n- Fixed response shape defined by server\n- **Over-fetching**: Gets more data than needed\n- **Under-fetching**: Needs multiple round-trips for related data\n\n\`\`\`bash\n# 3 separate requests for a user's posts with comments:\nGET /users/123\nGET /users/123/posts\nGET /posts/456/comments\n\`\`\`\n\n### GraphQL\n- Single endpoint: \`POST /graphql\`\n- Client specifies exact data shape\n- One round-trip for nested data\n\n\`\`\`graphql\n# One request:\nquery {\n  user(id: "123") {\n    name\n    posts {\n      title\n      comments { body }\n    }\n  }\n}\n\`\`\`\n\n### Comparison\n| | REST | GraphQL |\n|--|------|--------|\n| Endpoints | Multiple | Single |\n| Data fetching | Fixed shape | Client-specified |\n| Over-fetching | Common | Eliminated |\n| Caching | HTTP cache (easy) | Requires custom logic |\n| Type system | OpenAPI/manual | Built-in schema |\n| N+1 problem | Moderate | Worse (DataLoader needed) |\n| Learning curve | Low | Higher |\n\n### When NOT to Use GraphQL\n- Simple CRUD APIs with predictable data needs\n- Public APIs (REST is more universally understood)\n- High-throughput APIs (REST caching is better)`,
    eli5: "REST is like a restaurant menu — you order specific dishes and get exactly what's on the menu. GraphQL is like a custom sandwich shop — you tell them exactly what you want on your sandwich and get only that.",
    tags: JSON.stringify(["backend", "api-design", "rest", "graphql", "trade-offs"]),
  },
  {
    id: id(), channel: "backend", subChannel: "authentication", difficulty: "intermediate",
    question: "What is the difference between authentication and authorization? How do JWT tokens work?",
    answer: "Authentication verifies WHO you are (login). Authorization verifies WHAT you can do (permissions). JWT (JSON Web Token) is a self-contained token with three base64-encoded parts: Header (algorithm), Payload (claims like user ID and expiry), and Signature (HMAC of header+payload using secret). The server can verify JWTs without a database lookup because the signature is cryptographically verifiable.",
    explanation: `## Authentication vs Authorization\n\n| Concept | Question | Example |\n|---------|----------|---------|\n| **Authentication** | Who are you? | Login with username/password |\n| **Authorization** | What can you do? | Can this user delete a post? |\n\nAuthentication always happens before authorization.\n\n## JWT Structure\n\`header.payload.signature\`\n\n### Header\n\`\`\`json\n{ "alg": "HS256", "typ": "JWT" }\n→ Base64URL: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\n\`\`\`\n\n### Payload (Claims)\n\`\`\`json\n{\n  "sub": "user_123",    // Subject (user ID)\n  "name": "John Doe",\n  "role": "admin",\n  "iat": 1516239022,    // Issued at\n  "exp": 1516325422     // Expiry (1 day later)\n}\n\`\`\`\n\n### Signature\n\`\`\`\nHMACSHA256(\n  base64Url(header) + "." + base64Url(payload),\n  secretKey\n)\n\`\`\`\n\n## Verification Flow\n1. Client sends \`Authorization: Bearer <token>\` header\n2. Server decodes header + payload (public info)\n3. Server recomputes signature with secret\n4. If signatures match → token is authentic\n5. Check \`exp\` claim → token isn't expired\n6. No database lookup needed!\n\n## JWT vs Session Tokens\n| | JWT | Session |\n|--|-----|--------|\n| Storage | Stateless | Server-side DB |\n| Revocation | Hard (until expiry) | Easy (delete from DB) |\n| Scalability | Excellent (stateless) | Needs shared session store |\n| Size | Larger (~200-500 bytes) | Small (random ID) |`,
    eli5: "Authentication is like showing your passport at the border — it proves who you are. Authorization is like showing a ticket at a concert — it proves what you're allowed to do once you're in. A JWT is like a wristband with your info stamped in that anyone can read but no one can fake.",
    tags: JSON.stringify(["backend", "authentication", "jwt", "authorization", "security"]),
  },
  {
    id: id(), channel: "backend", subChannel: "caching", difficulty: "intermediate",
    question: "What is cache stampede (thundering herd) and how do you prevent it?",
    answer: "Cache stampede occurs when a popular cached key expires and many simultaneous requests all miss the cache, hitting the database concurrently and overwhelming it. Prevention: (1) Lock/mutex on cache miss — only one request fetches from DB, others wait, (2) Probabilistic early expiration — proactively refresh before expiry, (3) Background refresh — serve stale data while refreshing asynchronously.",
    explanation: `## Cache Stampede (Thundering Herd)\n\n### The Problem\n1. A key (e.g., homepage feed) is cached with 5-minute TTL\n2. TTL expires at exactly the same time\n3. 1000 concurrent requests all miss the cache simultaneously\n4. All 1000 hit the database → DB overwhelmed → cascading failure\n\n### Prevention Strategies\n\n#### 1. Mutex/Lock (Cache Locking)\n\`\`\`python\ndef get_data(key):\n    data = cache.get(key)\n    if data: return data\n    \n    # Try to acquire lock\n    if cache.set(key + ":lock", 1, nx=True, ex=10):\n        # We won the lock — fetch from DB\n        data = db.query(key)\n        cache.set(key, data, ex=300)\n        cache.delete(key + ":lock")\n    else:\n        # Lost the lock — wait and retry\n        time.sleep(0.1)\n        return get_data(key)  # Will hit cache now\n    return data\n\`\`\`\n\n#### 2. XFetch / Probabilistic Early Recomputation\n- Each request has a probability of refreshing early\n- Probability increases as TTL decreases\n- Stochastically distributes refresh load over time\n\n#### 3. Stale-While-Revalidate\n- Serve expired (stale) data immediately\n- Trigger background refresh\n- Next request gets fresh data\n\`\`\`python\nif expired(key):\n    refresh_in_background(key)  # Non-blocking\n    return stale_data  # Return immediately\n\`\`\`\n\n#### 4. Longer TTL + Cache-Aside with Jitter\n- Add random jitter to TTL: TTL = 300 + random(0, 60)\n- Different keys expire at different times → no synchronized misses`,
    eli5: "Imagine your school cafeteria runs out of pizza at noon. Suddenly 500 kids all rush to the kitchen at once. Cache stampede is the same — when a cached answer expires, everyone suddenly hits the database at once. The fix is to have only one person fetch more pizza while the others wait.",
    tags: JSON.stringify(["backend", "caching", "cache-stampede", "thundering-herd", "redis"]),
  },

  // ── DATABASE ──────────────────────────────────────────────────────────────
  {
    id: id(), channel: "database", subChannel: "indexing", difficulty: "intermediate",
    question: "What is a database index, how does a B-tree index work, and when should you NOT add an index?",
    answer: "An index is a separate data structure that speeds up queries by avoiding full table scans. B-tree indexes store values in a balanced tree where each lookup is O(log n). Don't add indexes on: (1) small tables (full scan is faster), (2) columns rarely used in WHERE/JOIN/ORDER BY, (3) tables with heavy write workloads (index maintenance adds overhead), (4) columns with very low cardinality (e.g., boolean columns).",
    explanation: `## Database Indexes\n\n### How B-Tree Index Works\nA B-tree (Balanced Search Tree) index stores sorted column values with pointers to actual rows:\n\n\`\`\`\n         [50]\n        /    \\\n     [25]    [75]\n    /   \\   /   \\\n  [10] [30][60] [90]\n\`\`\`\n\n- **Lookup**: O(log n) — binary search down the tree\n- **Range scans**: Walk leaf nodes left-to-right\n- **Insertion/Deletion**: O(log n) — tree rebalancing\n\n### Without Index: Full Table Scan\n\`\`\`sql\nSELECT * FROM orders WHERE customer_id = 12345;\n-- Reads EVERY row → O(n)\n\`\`\`\n\n### With Index\n\`\`\`sql\nCREATE INDEX idx_orders_customer ON orders(customer_id);\n-- Navigates B-tree → finds rows in O(log n)\n\`\`\`\n\n### When NOT to Index\n1. **Small tables** (<1000 rows): Seq scan is faster than index lookup\n2. **Low cardinality** (boolean, gender): Index gives little selectivity\n3. **Write-heavy tables**: Each INSERT/UPDATE/DELETE must update all indexes\n4. **Rarely queried columns**: Index takes space, provides no benefit\n\n### Index Types\n| Type | Best For |\n|------|----------|\n| B-tree | Equality, range queries (default) |\n| Hash | Exact equality only (faster lookup) |\n| GiST/GIN | Full-text search, JSON, arrays (PostgreSQL) |\n| Partial | Indexes a subset of rows |\n| Composite | Multiple column queries (column order matters!) |`,
    eli5: "A database index is like a book's index at the back — instead of reading every page to find 'photosynthesis', you look it up and jump straight to page 45. But if your book only has 5 pages, the index is more work than just reading it.",
    tags: JSON.stringify(["database", "indexing", "b-tree", "sql", "performance"]),
  },
  {
    id: id(), channel: "database", subChannel: "transactions", difficulty: "advanced",
    question: "Explain ACID properties. What are isolation levels and what anomalies does each prevent?",
    answer: "ACID: Atomicity (all or nothing), Consistency (valid state before and after), Isolation (concurrent transactions don't interfere), Durability (committed data persists). Isolation levels from weakest to strongest: Read Uncommitted → Read Committed → Repeatable Read → Serializable. Higher isolation = fewer anomalies but more contention.",
    explanation: `## ACID Properties\n\n| Property | Meaning | Example |\n|----------|---------|--------|\n| **Atomicity** | All operations succeed or all are rolled back | Bank transfer: debit + credit are one unit |\n| **Consistency** | DB goes from one valid state to another | Constraints, foreign keys maintained |\n| **Isolation** | Concurrent transactions don't see each other's uncommitted work | Two users booking the last seat |\n| **Durability** | Committed data survives crashes | Write-ahead log (WAL) ensures persistence |\n\n## Isolation Levels & Anomalies\n\n### Dirty Read\nReading another transaction's uncommitted data.\n\n### Non-Repeatable Read\nSame query returns different values within one transaction (another committed an UPDATE).\n\n### Phantom Read\nSame range query returns different rows within one transaction (another committed an INSERT/DELETE).\n\n| Level | Dirty Read | Non-Repeatable | Phantom |\n|-------|-----------|----------------|--------|\n| Read Uncommitted | ❌ Possible | ❌ Possible | ❌ Possible |\n| Read Committed | ✅ Prevented | ❌ Possible | ❌ Possible |\n| Repeatable Read | ✅ Prevented | ✅ Prevented | ❌ Possible |\n| Serializable | ✅ Prevented | ✅ Prevented | ✅ Prevented |\n\n### Real Defaults\n- PostgreSQL default: **Read Committed**\n- MySQL/InnoDB default: **Repeatable Read**\n- SQL Server default: **Read Committed**\n\n### Performance vs Safety\nHigher isolation → more locking → lower throughput. Choose based on your consistency requirements:\n- Reporting queries: Read Committed is usually fine\n- Financial transfers: Serializable or application-level locking\n- Session data: Read Committed`,
    eli5: "ACID is a promise databases make: they'll do all steps of a transaction or none of them, keep everything valid, not let transactions interfere with each other, and never lose committed data even if the server crashes.",
    tags: JSON.stringify(["database", "transactions", "acid", "isolation-levels", "sql"]),
  },

  // ── DEVOPS ────────────────────────────────────────────────────────────────
  {
    id: id(), channel: "devops", subChannel: "ci-cd", difficulty: "intermediate",
    question: "What is the difference between blue-green deployment and canary deployment? When would you choose each?",
    answer: "Blue-green: maintains two identical production environments (blue = current, green = new). Switch all traffic at once using load balancer. Simple rollback by flipping back. Canary: gradually routes a percentage of traffic to the new version (5% → 25% → 100%). Better for testing at scale, lower risk. Blue-green is simpler; canary gives more control and early failure detection.",
    explanation: `## Deployment Strategies\n\n### Blue-Green Deployment\n\n\`\`\`\nInternet → Load Balancer → [BLUE (v1.0)] ← active\n                         → [GREEN (v1.1)] ← idle\n\nAfter deploy:\nInternet → Load Balancer → [BLUE (v1.0)] ← idle\n                         → [GREEN (v1.1)] ← active\n\`\`\`\n\n**Process**:\n1. Deploy new version to idle (green) environment\n2. Run smoke tests on green\n3. Switch load balancer to green (instantaneous)\n4. If issues: switch back to blue immediately\n\n**Pros**: Zero downtime, instant rollback\n**Cons**: 2x infrastructure cost, no gradual validation\n\n### Canary Deployment\n\n\`\`\`\nInternet → Load Balancer → [v1.0] ← 95% traffic\n                         → [v1.1] ← 5% traffic (canary)\n\n// Gradually shift:\n// Day 1: 5%, Day 2: 25%, Day 3: 100%\n\`\`\`\n\n**Process**:\n1. Deploy new version alongside old\n2. Route small % of traffic (canary users)\n3. Monitor error rates, latency, business metrics\n4. If healthy → increase %; if bad → roll back\n\n**Pros**: Early failure detection, gradual risk\n**Cons**: More complex, requires feature flags or weighted routing\n\n### Comparison\n| | Blue-Green | Canary |\n|--|-----------|-------|\n| Rollback | Instant (flip switch) | Reduce traffic to 0% |\n| Risk | All-at-once switch | Gradual |\n| Cost | 2x infra | 2x infra temporarily |\n| Complexity | Low | Higher |\n| User validation | No | Yes (subset of real users) |`,
    eli5: "Blue-green is like having two identical restaurants. You build the new one secretly, then flip the sign all at once. Canary is like first serving the new menu to 5 tables, seeing if they love it, then gradually giving it to everyone.",
    tags: JSON.stringify(["devops", "ci-cd", "blue-green", "canary", "deployment"]),
  },

  // ── SECURITY ──────────────────────────────────────────────────────────────
  {
    id: id(), channel: "security", subChannel: "authentication", difficulty: "intermediate",
    question: "What is SQL injection and how do you prevent it? Give an example of a vulnerable query and its fix.",
    answer: "SQL injection occurs when user input is concatenated directly into SQL queries, letting attackers manipulate the query logic. Prevention: (1) Use parameterized queries (prepared statements) — the most reliable fix, (2) ORM with proper escaping, (3) Input validation, (4) Least privilege database accounts. Never concatenate user input directly into SQL strings.",
    explanation: `## SQL Injection\n\n### Vulnerable Code\n\`\`\`python\n# VULNERABLE: string concatenation\nusername = request.form['username']  # Attacker inputs: admin' --\nquery = f"SELECT * FROM users WHERE username = '{username}'\"\ncursor.execute(query)\n# Resulting SQL:\n# SELECT * FROM users WHERE username = 'admin' --'\n# The -- comments out the rest, bypassing any password check!\n\`\`\`\n\n### Attack Examples\n- Login bypass: \`admin' --\` → logs in as admin without password\n- Data extraction: \`' UNION SELECT password FROM users --\`\n- Data destruction: \`'; DROP TABLE users --\`\n\n### Prevention: Parameterized Queries\n\`\`\`python\n# SAFE: parameterized query\ncursor.execute(\n    "SELECT * FROM users WHERE username = %s AND password = %s",\n    (username, password)  # Values never become SQL code\n)\n\n# Python sqlite3\ncursor.execute(\n    "SELECT * FROM users WHERE username = ?",\n    (username,)\n)\n\`\`\`\n\n### Why Parameterized Queries Work\nThe database driver sends the query template and parameters separately. The DB treats parameters as DATA, never as SQL code. No amount of SQL syntax in the parameter can change the query structure.\n\n### Defense in Depth\n1. **Parameterized queries** (primary defense)\n2. **Stored procedures** (if parameterized)\n3. **Input validation** (allowlist, not blocklist)\n4. **Least privilege**: DB account should only have SELECT/INSERT on needed tables\n5. **WAF**: Web Application Firewall as a secondary layer\n6. **Error handling**: Never expose DB errors to users`,
    eli5: "SQL injection is like filling out a form that asks for your name but writing a secret command instead. The computer follows the command and does things it shouldn't. The fix is to always treat user input as just text, never as instructions.",
    tags: JSON.stringify(["security", "sql-injection", "web-security", "owasp", "parameterized-queries"]),
  },

  // ── MACHINE LEARNING ──────────────────────────────────────────────────────
  {
    id: id(), channel: "machine-learning", subChannel: "supervised-learning", difficulty: "intermediate",
    question: "What is the bias-variance tradeoff in machine learning? How do overfitting and underfitting relate to it?",
    answer: "Bias measures how far off predictions are from true values (systematic error). Variance measures how much predictions vary for different training sets. High bias → underfitting (model too simple, misses patterns). High variance → overfitting (model too complex, memorizes training data but fails on new data). The goal is to find the sweet spot minimizing both.",
    explanation: `## Bias-Variance Tradeoff\n\n### Definitions\n- **Bias**: Error from wrong assumptions in the model. A model with high bias pays little attention to training data and oversimplifies.\n- **Variance**: Error from sensitivity to small fluctuations in training data. A model with high variance overfits noise.\n\n### Expected Error Decomposition\n\`\`\`\nExpected Error = Bias² + Variance + Irreducible Noise\n\`\`\`\n\n### Underfitting (High Bias)\n- Model is too simple (e.g., linear regression on non-linear data)\n- High training error AND high test error\n- Fix: Add more features, use more complex model, reduce regularization\n\n### Overfitting (High Variance)\n- Model memorizes training data including noise\n- Low training error but HIGH test error\n- Fix: More training data, regularization (L1/L2), dropout, early stopping, simpler model\n\n### The Tradeoff\n\`\`\`\nModel Complexity →\n\nError    Underfitting    Sweet Spot    Overfitting\n  ↑     ┌─────────────────────────────────────────\n  │     │  Total Error\n  │     │         \\      ___/\n  │     │    Bias² \\____/  Variance\n  │     │          min\n  │     └─────────────────────────────────────────\n\`\`\`\n\n### Detecting\n| | Train Error | Test Error |\n|--|------------|------------|\n| Good fit | Low | Low |\n| Underfitting | High | High |\n| Overfitting | Low | High |`,
    eli5: "Bias is when a student guesses all answers the same way (too simple). Variance is when a student memorizes the practice test exactly and fails the real test. The sweet spot is studying smart enough to understand patterns without memorizing.",
    tags: JSON.stringify(["machine-learning", "supervised-learning", "bias-variance", "overfitting", "underfitting"]),
  },
  {
    id: id(), channel: "machine-learning", subChannel: "model-evaluation", difficulty: "intermediate",
    question: "When should you use precision vs recall vs F1 score vs AUC-ROC? Give a real-world example for each.",
    answer: "Precision = TP/(TP+FP): use when false positives are costly (spam filter — blocking real email is bad). Recall = TP/(TP+FN): use when false negatives are costly (cancer screening — missing cancer is worse). F1 = harmonic mean of precision/recall: use when you need balance and classes are imbalanced. AUC-ROC: use to compare models across all thresholds, regardless of class balance.",
    explanation: `## Classification Metrics\n\n### Confusion Matrix\n\`\`\`\n              Predicted Positive  Predicted Negative\nActual Pos.        TP                  FN\nActual Neg.        FP                  TN\n\`\`\`\n\n### Metrics\n| Metric | Formula | High Value Means |\n|--------|---------|------------------|\n| Precision | TP/(TP+FP) | Few false alarms |\n| Recall | TP/(TP+FN) | Few missed positives |\n| F1 Score | 2×(P×R)/(P+R) | Balance of both |\n| Accuracy | (TP+TN)/Total | Overall correctness |\n\n### When to Use Each\n\n**Precision** (minimize false positives):\n- **Spam detection**: Don't block real emails\n- **Fraud alerts**: Don't block legitimate transactions unnecessarily\n- Motto: "Don't cry wolf"\n\n**Recall** (minimize false negatives):\n- **Cancer screening**: Never miss a real case\n- **Terrorist watchlist**: Don't miss a real threat\n- Motto: "Catch everything"\n\n**F1 Score**:\n- Imbalanced classes (99% negative, 1% positive)\n- When you need both precision and recall\n- Fraud detection (balance FP cost vs FN cost)\n\n**AUC-ROC** (Area Under Curve - Receiver Operating Characteristic):\n- Compare models without choosing a specific threshold\n- AUC = 1.0: perfect classifier; 0.5: random guessing\n- Good for: model selection, credit scoring, ranking problems\n\n### Precision-Recall Tradeoff\nLowering threshold → higher recall, lower precision\nRaising threshold → higher precision, lower recall`,
    eli5: "Precision is about not crying wolf — if you say it's cancer, it really is. Recall is about not missing real cases — catch every cancer even if you have some false alarms. F1 balances both. AUC tells you how good your model is overall without picking a specific cutoff.",
    tags: JSON.stringify(["machine-learning", "model-evaluation", "precision", "recall", "f1", "auc-roc"]),
  },

  // ── GENERATIVE AI ─────────────────────────────────────────────────────────
  {
    id: id(), channel: "generative-ai", subChannel: "llms", difficulty: "intermediate",
    question: "What is RAG (Retrieval-Augmented Generation) and why is it preferred over fine-tuning for knowledge-intensive tasks?",
    answer: "RAG combines a retrieval system (vector database) with an LLM. At query time, relevant documents are retrieved and injected into the LLM's context. Advantages over fine-tuning: (1) No retraining needed when data changes — just update the vector store, (2) Reduces hallucinations by grounding responses in actual documents, (3) Cheaper than fine-tuning, (4) Sources are citeable/traceable.",
    explanation: `## RAG — Retrieval-Augmented Generation\n\n### Architecture\n\`\`\`\nUser Query\n    │\n    ├─→ Embedding Model → Query Vector\n    │                           │\n    │                     Vector DB (Search)\n    │                           │\n    │                    Top-k Documents\n    │\n    └─→ LLM ← [Query + Documents] → Response\n\`\`\`\n\n### How It Works\n1. **Indexing** (offline): Chunk documents → embed each chunk → store in vector DB\n2. **Retrieval** (online): Embed query → similarity search → retrieve top-k chunks\n3. **Generation**: Pass query + retrieved chunks to LLM → generate grounded response\n\n### RAG vs Fine-Tuning\n| | RAG | Fine-Tuning |\n|--|-----|------------|\n| Updates | Instant (add to vector DB) | Requires retraining |\n| Cost | Low (inference only) | High (training compute) |\n| Hallucination | Reduced (grounded) | Still possible |\n| Private data | Yes | Yes (but baked into weights) |\n| Citeability | ✅ Yes (source chunks) | ❌ No |\n| Reasoning style | Unchanged | Can change model behavior |\n\n### Chunking Strategies\n- **Fixed size**: 512 tokens with 50-token overlap\n- **Semantic**: Split at paragraph/sentence boundaries\n- **Hierarchical**: Parent-child chunks for different retrieval granularities\n\n### Real-World Systems\n- **ChatGPT with browsing**: Web search + generation\n- **GitHub Copilot**: Code retrieval from your codebase\n- **Legal AI**: Case law retrieval + answer synthesis`,
    eli5: "RAG is like giving an AI a library card. Instead of memorizing everything upfront, when you ask a question it first looks up the relevant pages, then uses those pages to write you an answer. Much more accurate and up-to-date than memorizing a textbook.",
    tags: JSON.stringify(["generative-ai", "rag", "llms", "vector-database", "embeddings"]),
  },
  {
    id: id(), channel: "generative-ai", subChannel: "transformer-architecture", difficulty: "advanced",
    question: "How does the attention mechanism work in transformers? What problem does self-attention solve that RNNs had?",
    answer: "Self-attention computes a weighted sum of all tokens in a sequence, where weights represent how relevant each token is to the current token (Q·K/√d_k, then softmax, then ×V). This solves the key RNN problem: vanishing gradients over long sequences. Attention can directly connect any two tokens regardless of distance, while RNNs process sequentially and lose long-range context.",
    explanation: `## Attention Mechanism\n\n### The RNN Problem\nRNNs process tokens one by one: hidden state carries information forward. For a 1000-token sequence, information from token 1 must survive 999 updates — it gets diluted (vanishing gradient).\n\n### Self-Attention Formula\n\`\`\`\nAttention(Q, K, V) = softmax(Q × K^T / √d_k) × V\n\`\`\`\n\n- **Q** (Query): "What am I looking for?"\n- **K** (Key): "What do I have?"\n- **V** (Value): "What do I give you?"\n- **√d_k**: Scaling factor to prevent softmax saturation\n\n### Example: "The cat sat on the mat because it was tired"\n- Token "it" attends strongly to "cat" → model resolves the pronoun\n- Direct connection regardless of distance (no sequential processing)\n\n### Step by Step\n\`\`\`python\nimport torch\nimport torch.nn.functional as F\n\ndef attention(Q, K, V, d_k):\n    # Q: [seq_len, d_k], K: [seq_len, d_k], V: [seq_len, d_v]\n    scores = Q @ K.T / (d_k ** 0.5)  # [seq_len, seq_len]\n    weights = F.softmax(scores, dim=-1)  # Attention weights\n    return weights @ V  # [seq_len, d_v]\n\`\`\`\n\n### Multi-Head Attention\nRun attention h times in parallel with different learned Q/K/V projections. Each head learns different relationships (syntax, semantics, coreference).\n\n### RNN vs Transformer\n| | RNN/LSTM | Transformer |\n|--|----------|-------------|\n| Long-range deps. | Weak (vanishing grad) | Strong (direct attention) |\n| Parallelization | Sequential (slow training) | Parallel (fast training) |\n| Context window | Limited | Fixed max (4k-128k) |\n| Parameters | Fewer | Many more |`,
    eli5: "Attention lets every word in a sentence look at every other word and decide how important it is. Old systems had to read words one at a time and often forgot the beginning by the end. Attention is like having a highlighter — you can mark any word as important for understanding any other word.",
    tags: JSON.stringify(["generative-ai", "transformer-architecture", "attention", "llms", "self-attention"]),
  },

  // ── BEHAVIORAL ────────────────────────────────────────────────────────────
  {
    id: id(), channel: "behavioral", subChannel: "leadership", difficulty: "intermediate",
    question: "Tell me about a time you had to deliver difficult feedback to a peer or team member. How did you handle it and what was the outcome?",
    answer: "Use the STAR method: describe a specific Situation where a peer's work quality or behavior was impacting the team, Task (your responsibility to address it), Action (private, direct, empathetic conversation focused on behaviors not personality, with specific examples), Result (improved behavior, maintained relationship, or how you escalated if needed). Key: lead with curiosity, not judgment.",
    explanation: `## Delivering Difficult Feedback — STAR Framework\n\n### What Interviewers Look For\n- Emotional intelligence: addressed it directly without being aggressive\n- Specificity: used concrete examples, not vague complaints\n- Outcome orientation: focused on growth, not punishment\n- Courage: didn't avoid a hard conversation\n\n### Strong STAR Example Structure\n\n**Situation**: "On a critical project, a teammate was consistently missing sprint deadlines and their code was causing frequent CI failures for the team."\n\n**Task**: "As the tech lead, it was my responsibility to address this before it impacted the release."\n\n**Action**:\n1. Requested a private 1:1 meeting (never public shaming)\n2. Asked open-ended questions first: "How are you finding the workload?"\n3. Shared specific observations: "In the last 3 sprints, the CI has failed 7 times from your PRs"\n4. Asked for their perspective before proposing solutions\n5. Collaboratively created an action plan (pair programming, reduced scope)\n\n**Result**: "Over the next 2 sprints, their PR quality significantly improved. They later shared that they'd been dealing with unclear requirements and my feedback helped them ask for clarification earlier."\n\n### Key Principles\n- **Private**: Never feedback in public or Slack channels\n- **Specific**: "Your last 3 PRs had no tests" not "you write bad code"\n- **Behavioral**: "The report was submitted 2 days late" not "you're unreliable"\n- **Timely**: Address it close to when it happened\n- **Two-way**: Listen to their perspective — you might be wrong\n\n### Red Flags to Avoid\n- Saying you've never given difficult feedback\n- Claiming conflict always resolved perfectly\n- Speaking negatively about the person rather than the behavior`,
    eli5: "When someone isn't doing well at work, you talk to them privately and kindly, give them specific examples of what you observed, listen to their side, and work together on a plan to improve.",
    tags: JSON.stringify(["behavioral", "leadership", "feedback", "star-method", "conflict-resolution"]),
  },
  {
    id: id(), channel: "behavioral", subChannel: "failure-handling", difficulty: "intermediate",
    question: "Tell me about a time you made a significant technical mistake. What happened and what did you learn?",
    answer: "Choose a real example where you had agency. Structure: what the mistake was (without blaming others), immediate actions you took to mitigate impact, root cause analysis, and concrete changes you made afterward. Show: ownership, resilience, and systematic thinking. Avoid: choosing trivial mistakes, blaming others, or dwelling too long on the mistake vs the learning.",
    explanation: `## Mistake/Failure Questions — What Interviewers Want\n\n### Why They Ask\n- Can you own mistakes without becoming defensive?\n- Do you learn systematically or repeat the same errors?\n- How do you handle pressure and adversity?\n- Do you have good judgment about what constitutes a "significant" mistake?\n\n### Strong Response Structure\n\n**1. The Mistake** (be specific, own it fully)\n"During a database migration, I didn't account for a foreign key constraint that caused the migration to fail mid-way, leaving the DB in an inconsistent state during peak hours."\n\n**2. Immediate Actions** (shows crisis management)\n"I immediately alerted the team, rolled back the partial migration using our backup, and spent 2 hours verifying data integrity before bringing the service back online."\n\n**3. Root Cause** (shows analytical thinking)\n"Root cause: I had tested on a copy of the DB that was 2 months old and didn't have the constraint that was added recently. I also didn't have a dry-run of the migration on staging."\n\n**4. Prevention** (most important — what changed?)\n"Afterward I: (1) Added a mandatory pre-flight checklist for all migrations, (2) Required staging validation < 24h before production, (3) Implemented a blue-green migration strategy for future zero-downtime migrations."\n\n### Calibrating Mistake Severity\n- Too trivial: "I once pushed to the wrong branch" — doesn't show real stakes\n- Too severe without ownership: blaming others\n- Just right: Real impact you had agency over, clear learning\n\n### Language to Use\n- "I should have..." (ownership)\n- "What I learned was..." (growth mindset)\n- "Since then I always..." (changed behavior)`,
    eli5: "When you make a mistake, interviewers want to see that you own it, fix it quickly, understand why it happened, and change your process so it doesn't happen again.",
    tags: JSON.stringify(["behavioral", "failure-handling", "star-method", "ownership", "growth-mindset"]),
  },
];

async function main() {
  console.log(`Seeding ${questions.length} questions (backend, database, devops, security, ML, gen-ai, behavioral)...`);
  let count = 0;
  for (const q of questions) {
    await client.execute({
      sql: `INSERT OR IGNORE INTO questions
        (id, question, answer, explanation, eli5, difficulty, tags, channel, sub_channel, status, is_new, created_at, last_updated)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,
      args: [q.id, q.question, q.answer, q.explanation, q.eli5 ?? null, q.difficulty, q.tags, q.channel, q.subChannel, "active", 1, NOW, NOW],
    });
    count++;
    console.log(`[${q.channel}] ${q.question.slice(0, 60)}...`);
  }
  console.log(`\nDone! ${count} questions inserted.`);
  client.close();
}
main().catch((e) => { console.error(e); process.exit(1); });
